### ISSUE TITLE
Repository Ownership Transfer

### ISSUE THREAD

**Issue by pyieh** [jenkins-infra/repository-permissions-updater#2338]
@pyieh and @ramapalani signing on as new owners of the [mask-passwords plugin](https://github.com/jenkinsci/mask-passwords-plugin), taking over for @oleg-nenashev 

Unique Name Feature PR:
https://github.com/jenkinsci/mask-passwords-plugin/pull/25
Original HOSTING JIRA discussion:
https://issues.jenkins.io/browse/HOSTING-1144

**Comment by timja** [comment]
no need to raise an issue here
