### ISSUE TITLE
Hosting Request: ECU-TEST Execution plugin

### ISSUE THREAD

**Issue by TT-S3-D1** [jenkins-infra/repository-permissions-updater#2344]
### Repository URL

https://github.com/tracetronic/ecu-test-execution-plugin

### New Repository Name

ecu-test-execution-plugin

### Description

This plugin enables a platform-independent test execution. Due to the reduced complexity and communication via REST API, it provides an easy and reliable entry into continuous testing. It integrates ECU-TEST with Jenkins and allows report generation and its upload of automated test execution.

### GitHub users to have commit permission

TT-S3-D1
TT-CX-User
MartinGroscheTT
cwellmtt
thardtke-tt
cpoenisch

### Jenkins project users to have release permission

tracetronic

### Issue tracker

GitHub issues

**Comment by timja** [comment]
Please pick one build system, don't use maven and gradle

**Comment by TT-S3-D1** [comment]
Hi @timja 
Can you please explain for me the last required issue? I can't understand why the build.gradle shouldn't be parseable. At https://github.com/tracetronic/ecu-test-execution-plugin/runs/6782691306?check_suite_focus=true is a successful gradle run for that.
Thanks a lot.
Best
Sebastian

**Comment by timja** [comment]
Hey not sure from a quick look but this should be changed to log the exception:
https://github.com/jenkins-infra/repository-permissions-updater/blob/ab78d28ae2ebb66d989750619ae5b7d49c0bc9b3/src/main/java/io/jenkins/infra/repository_permissions_updater/hosting/GradleVerifier.java#L142

I don't have time right now but should be a small change

**Comment by TT-S3-D1** [comment]
Hi @timja,
sorry for interrupting you again. 
Can you or maybe someone else of the jenkins-infra team help at this point? I think the required change conflicts with the hint. 
Thanks a lot!
Best Regards
Sebastian

**Comment by yaroslavafenkin** [comment]
CERT will have a deeper look. Tracked internally as JENSEC-1864.

**Comment by yaroslavafenkin** [comment]
@TT-S3-D1,

We've had a deeper look and haven't found any vulnerabilities in the code.

Dependency scan has identified issues with `org.jetbrains.kotlin:kotlin-stdlib@1.4.10` which is supplied by `com.squareup.okhttp3:logging-interceptor@4.9.3` and `com.squareup.okhttp3:okhttp@4.9.3`, and `com.google.guava:guava@11.0.1`.

Please confirm that you're no affected by those, or otherwise consider updating to a fixed version.

If you have any further questions please feel free to ask.

**Comment by TT-S3-D1** [comment]
@yaroslavafenkin 
thanks for the hint - I've updated all dependency versions

**Comment by timja** [comment]
@yaroslavafenkin did you want to re-check?

**Comment by yaroslavafenkin** [comment]
> @yaroslavafenkin did you want to re-check?

Re-checked, looks alright to me.
