### ISSUE TITLE
Request to access aws-codepipeline-plugin repository

### ISSUE THREAD

**Issue by KyleBarton** [jenkins-infra/repository-permissions-updater#2353]
### Repository URL

https://github.com/jenkinsci/aws-codepipeline-plugin

### New Repository Name

aws-codepipeline-plugin-repository

### Description

As a member of the AWS CodePipeline team, I'd like to request access to make and release changes to jenkinsci/aws-codepipeline-plugin for my team.

### GitHub users to have commit permission

@KyleBarton

### Jenkins project users to have release permission

kybarton_amazon

### Issue tracker

GitHub issues

**Comment by KyleBarton** [comment]
The below two requirements are confusing to me, since this is not a request to host a new plugin, rather to obtain access to an existing plugin:

⛔ Required: The 'artifactId' from the pom.xml (aws-codepipeline) is incorrect, it should be aws-codepipeline-repository ('New Repository Name' field with "-plugin" removed)
⛔ Required: 'New Repository Name' must end with "-plugin" (disregard if you are not requesting hosting of a plugin)

What are the implications of renaming this plugin in the Jenkins ecosystem? Will existing users have their workflows disrupted?

**Comment by timja** [comment]
This template is just for a new plugin hosting request. You need to send a pull request to the permissions file for the plugin in this repo to get added
