### ISSUE TITLE
🏠 Hosting request: Generic Event Plugin

### ISSUE THREAD

**Issue by JohnNiang** [jenkins-infra/repository-permissions-updater#2356]
### Repository URL

https://github.com/johnniang/generic-event-plugin

### New Repository Name

generic-event-plugin

### Description

The Generic Event Plugin built for Jenkins is mainly to solve the interaction problem between the third-party system and Jenkins.

By using the plugin, the third-party system can receive the events it is interested in more quickly and respond quickly.

At present, our event body mainly refers to CloudEvents, and CloudEvents specification may be supported in the future. We look forward to more people to push this goal.

### GitHub users to have commit permission

@johnniang
@LinuxSuRen 

### Jenkins project users to have release permission

johnniang
surenpi

### Issue tracker

GitHub issues

**Comment by timja** [comment]
Have you seen this? https://github.com/jenkinsci/cloudevents-plugin

Would it be better to improve that plugin than creating a new one doing similar?

**Comment by timja** [comment]
@Wadeck can you let us know if you want to review this please?

**Comment by Wadeck** [comment]
@timja No I am fine with it :) I checked quickly the code, I found nothing that could require a deeper audit.

**Comment by JohnNiang** [comment]
> 

Thanks for your reminder! I have tried to interact with https://github.com/jenkinsci/cloudevents-plugin, but it seems to be inactive. 

The plugin I wrote would be simpler, more flexible and more extensible.

**Comment by timja** [comment]
Where have you interacted with it? You could also take that plugin over yourself?

We prefer not to have multiple plugins doing the same thing :)

**Comment by JohnNiang** [comment]
Hi @timja : P
1. You can see https://github.com/jenkinsci/cloudevents-plugin/issues/13
2. Those two plugins have totally different response structures. If I take that plugin over myself, I have to consider the backward compatibility. It's very tricky for me.

**Comment by timja** [comment]
@waveywaves / @ShrutiC-git any opinions?

**Comment by LinuxSuRen** [comment]
IMO, the Cloudevent is great, it can be a standard. But it is also a little bit complex if users only want to receive some events of Jenkins.

+ 1 from me to support have a generic Jenkins event plugin

**Comment by timja** [comment]
will leave this for a week or so to give people time to reply, and if no feedback in that time then will host.

(ping me back if I forget)

**Comment by JohnNiang** [comment]
Hi @timja , I encountered two issues here recently, please help me out!

> I have read https://github.com/jenkins-infra/repository-permissions-updater/issues/2356#issuecomment-1037258266

1. I haven't received any invitation to the Jenkins CI Org on GitHub. So that I have no commit permission to my plugin.
2. Although #2374 got merged, I have no upload permission to artifactory. Please see the logs below after I tried to release my plugin according to https://www.jenkins.io/doc/developer/publishing/releasing-manually/:

      ```java
          Downloaded from central: https://repo.jenkins-ci.org/artifactory/remote-snapshot-repos/org/codehaus/plexus/plexus-java/1.1.0/plexus-java-1.1.0.jar (53 kB at 32 kB/s)
          [INFO] No previous run data found, generating javadoc.
          [INFO] 
          1 warning
          [WARNING] Javadoc Warnings
          [WARNING] warning: unknown enum constant When.ALWAYS
          [WARNING] reason: class file for javax.annotation.meta.When not found
          [INFO] Building jar: /home/johnniang/workspaces/jenkinsci/generic-event-plugin/target/checkout/target/generic-event-javadoc.jar
          [INFO] 
          [INFO] >>> spotbugs-maven-plugin:4.2.3:check (spotbugs) > :spotbugs @ generic-event >>>
          [INFO] 
          [INFO] --- spotbugs-maven-plugin:4.2.3:spotbugs (spotbugs) @ generic-event ---
          [INFO] 
          [INFO] <<< spotbugs-maven-plugin:4.2.3:check (spotbugs) < :spotbugs @ generic-event <<<
          [INFO] 
          [INFO] 
          [INFO] --- spotbugs-maven-plugin:4.2.3:check (spotbugs) @ generic-event ---
          [INFO] 
          [INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ generic-event ---
          [INFO] Installing /home/johnniang/workspaces/jenkinsci/generic-event-plugin/target/checkout/target/generic-event.hpi to /home/johnniang/.m2/repository/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2.hpi
          [INFO] Installing /home/johnniang/workspaces/jenkinsci/generic-event-plugin/target/checkout/target/generic-event-0.0.2.pom to /home/johnniang/.m2/repository/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2.pom
          [INFO] Installing /home/johnniang/workspaces/jenkinsci/generic-event-plugin/target/checkout/target/generic-event.jar to /home/johnniang/.m2/repository/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2.jar
          [INFO] Installing /home/johnniang/workspaces/jenkinsci/generic-event-plugin/target/checkout/target/generic-event-sources.jar to /home/johnniang/.m2/repository/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2-sources.jar
          [INFO] Installing /home/johnniang/workspaces/jenkinsci/generic-event-plugin/target/checkout/target/generic-event-javadoc.jar to /home/johnniang/.m2/repository/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2-javadoc.jar
          [INFO] 
          [INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ generic-event ---
          Uploading to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2.hpi
          Uploading to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2.pom
          [INFO] ------------------------------------------------------------------------
          [INFO] BUILD FAILURE
          [INFO] ------------------------------------------------------------------------
          [INFO] Total time:  30.623 s
          [INFO] Finished at: 2022-02-22T11:05:04+08:00
          [INFO] ------------------------------------------------------------------------
          [WARNING] The requested profile "consume-incrementals" could not be activated because it does not exist.
          [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project generic-event: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:generic-event:hpi:0.0.2 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/io/jenkins/plugins/generic-event/0.0.2/generic-event-0.0.2.hpi, status: 401 Unauthorized -> [Help 1]
          [ERROR] 
          [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
          [ERROR] Re-run Maven using the -X switch to enable full debug logging.
          [ERROR] 
          [ERROR] For more information about the errors and possible solutions, please read the following articles:
          [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
      ```

**Comment by timja** [comment]
I've sent you an invite

Follow troubleshooting:
https://www.jenkins.io/doc/developer/publishing/releasing-manually/#troubleshooting

If you're still stuck post on the dev mailing list or switch to https://www.jenkins.io/doc/developer/publishing/releasing-cd/
