### ISSUE TITLE
commons-lang-api plugin

### ISSUE THREAD

**Issue by nhojpatrick** [jenkins-infra/repository-permissions-updater#2372]
### Repository URL

https://github.com/nhojpatrick/jenkinsci_commons-lang-api-plugin

### New Repository Name

commons-lang-api-plugin

### Description

Creation of api-plugin, as discussed here https://github.com/jenkinsci/jenkins/pull/6267 and here https://github.com/jenkinsci/jenkins/pull/6270.

I want the the plugin to support the version oldest jenkins avaliable so easier for plugins to move over without themselves having to upgrade. Once every 'active' plugin updated, plan to upgrade this plugin to newer recent version.

This is my 1st attempt at creating a jenkins plugin, so probably lots needs tweaking.

### GitHub users to have commit permission

nhojpatrick

### Jenkins project users to have release permission

nhojpatrick

### Issue tracker

GitHub issues

**Comment by nhojpatrick** [comment]
It does have README.md, LICENSE and pom.xml.
Could this be expected branch name issue as I've stopped using master and default is now main.

**Comment by nhojpatrick** [comment]
issue creating 2 requests at the same time, i was pushing both local branches to the same remote repo

**Comment by timja** [comment]
Same issues as https://github.com/jenkins-infra/repository-permissions-updater/issues/2373

**Comment by nhojpatrick** [comment]
@timja should be update like #2373

**Comment by timja** [comment]
On top of what the bot said:

You'll need to update the co-ordinates in your README after group ID changed
I would suggest looking at enabling [jenkins.io/doc/developer/publishing/releasing-cd](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) along with dependabot
