### ISSUE TITLE
commons-lang3-api plugin

### ISSUE THREAD

**Issue by nhojpatrick** [jenkins-infra/repository-permissions-updater#2373]
### Repository URL

https://github.com/nhojpatrick/jenkinsci_commons-lang3-api-plugin

### New Repository Name

commons-lang3-api-plugin

### Description

Creation of api-plugin, as discussed here https://github.com/jenkinsci/jenkins/pull/6267 and here https://github.com/jenkinsci/jenkins/pull/6270.

I want the the plugin to support the version oldest jenkins avaliable so easier for plugins to move over without themselves having to upgrade. Once every 'active' plugin updated, plan to upgrade this plugin to newer recent version.

But this is for commons-lang3.

This is my 2nd attempt at creating a jenkins plugin, so probably lots needs tweaking.

### GitHub users to have commit permission

nhojpatrick

### Jenkins project users to have release permission

nhojpatrick

### Issue tracker

GitHub issues

**Comment by timja** [comment]
1. URL should be the GitHub repo: https://github.com/nhojpatrick/jenkinsci_commons-lang3-api-plugin/blob/21fd2b599084f35ac6d129ab8b8a8ba213fb9f19/pom.xml#L21 replace with https://github.com/jenkinsci/commons-lang3-api-plugin
2. you should use the latest parent pom not the minimum version that the hosting checker is requiring, https://github.com/nhojpatrick/jenkinsci_commons-lang3-api-plugin/blob/21fd2b599084f35ac6d129ab8b8a8ba213fb9f19/pom.xml#L7, see https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.34
3. All URLs in the pom file should use https, https://github.com/nhojpatrick/jenkinsci_commons-lang3-api-plugin/blob/21fd2b599084f35ac6d129ab8b8a8ba213fb9f19/pom.xml#L25

**Comment by timja** [comment]
Group ID should be `io.jenkins.plugins`

**Comment by nhojpatrick** [comment]
@timja groupId was bad refactor from github-actions comment
1. I did wonder about that, but just followed the template
2. parent update done, ideally wanted oldest so easier for other plugins to integrate without having to be force to update.
3. MIT license use http in archetype so assumed was fine

**Comment by timja** [comment]
Is it possible you used a really old archetype version?

> 1. I did wonder about that, but just followed the template

Template uses GitHub: https://github.com/jenkinsci/archetypes/blob/63871c221b388df45c4eb7015701319a90179e22/empty-plugin/src/main/resources/archetype-resources/pom.xml#L15

> 2\. parent update done, ideally wanted oldest so easier for other plugins to integrate without having to be force to update.

Generally parent pom doesn't affect what version you can use at all.

> 3\. MIT license use http in archetype so assumed was fine

Not as far as I can tell, it was updated 4 years ago in https://github.com/jenkinsci/archetypes/commit/a4b64f680df2a17519a7fe3ba33b10051592cdd7
