### ISSUE TITLE
openshift-token-kubernetes-credentials-plugin

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/repository-permissions-updater#2381]
### Repository URL

https://github.com/jonesbusy/openshift-token-kubernetes-credentials-plugin

### New Repository Name

openshift-token-kubernetes-credentials-plugin

### Description

This plugin provides an extension for the [kubernetes-credentials-provider-plugin](https://github.com/jenkinsci/kubernetes-credentials-provider-plugin) plugin, and the [openshift-client-plugin](https://github.com/jenkinsci/openshift-client-plugin) that extend the kubernetes credentials provider to create the special credential type required by the openshift-client-plugin when interacting with an openshift cluster.

![openshift_token](https://user-images.githubusercontent.com/825750/154024409-2ca7e5b9-e9f0-4cc3-a1fd-327978365d92.PNG)

It's very similar to the existing plugin : https://github.com/jenkinsci/bitbucket-kubernetes-credentials-plugin for Bitbucket credentials.

### GitHub users to have commit permission

jonesbusy

### Jenkins project users to have release permission

jonesbusy

### Issue tracker

GitHub issues

**Comment by timja** [comment]
@jtnord this look sane to you?

https://github.com/jonesbusy/openshift-token-kubernetes-credentials-plugin/blob/main/src/main/java/ch/jonesbusy/jenkins/openshiftcredentialsk8s/OpenshiftTokenCredentialConverter.java

**Comment by timja** [comment]
Not sure where your Jenkinsfile came from but it's using a removed `findbugs` option.

This is our default recommendation:

https://github.com/jenkinsci/archetypes/blob/master/common-files/Jenkinsfile#L5

**Comment by jonesbusy** [comment]
@timja Fixed thanks. Was coming from this plugin : https://github.com/jenkinsci/bitbucket-kubernetes-credentials-plugin/blob/master/Jenkinsfile

**Comment by timja** [comment]
Sure you may want to review the other templates then or re-create from the archetype (empty-plugin):
https://github.com/jenkinsci/archetypes/tree/master/common-files


https://github.com/jenkinsci/archetypes

**Comment by timja** [comment]
You're missing `<url>` in the `pom.xml` so you won't get documentation on the plugin site.

**Comment by jonesbusy** [comment]
@timja I've updated .gitignore, readme, license and github actions. Thanks for the support

**Comment by timja** [comment]
Ok, it's also recommended that you avoid powermock as it doesn't work on Java 17 out of the box.

and to use mockito instead but not a blocker

see https://github.com/jenkinsci/plugin-pom/pull/442#issue-1002043253

**Comment by jonesbusy** [comment]
@timja Good point. I updated Mockito at got rid of Powermock

**Comment by timja** [comment]
not sure if this works but going to try it after https://github.com/jenkins-infra/repository-permissions-updater/pull/2388 was merged

**Comment by jtnord** [comment]
> @jtnord this look sane to you?
> 
> https://github.com/jonesbusy/openshift-token-kubernetes-credentials-plugin/blob/main/src/main/java/ch/jonesbusy/jenkins/openshiftcredentialsk8s/OpenshiftTokenCredentialConverter.java

It does, but when I get around to writing the provider to not store everything in memory and load on demand it may break if cannot keep API compatability, but c'est la vie
