### ISSUE TITLE
Disallow too long artifact and group ids to be longer than 100 characters

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/repository-permissions-updater#2387]
Full thread - https://github.com/jenkins-infra/update-center2/pull/551#issuecomment-955194014

> So any rule should be 109 >= len(groupId) + 2*len(artifactId) (or stricter). With io.jenkins.plugins (18 chars) as the "default" groupId, that leaves ~45 chars for most artifactIds.

I think we can make it simple and say no more than 45 characters for either field, but the above formula is awesome and precise

**Comment by timja** [comment]
The check is defined here:

https://github.com/jenkins-infra/repository-permissions-updater/blob/e3abb0ea9cd32b895455e045297c96233023234d/src/main/java/io/jenkins/infra/repository_permissions_updater/hosting/MavenVerifier.java#L30

and

https://github.com/jenkins-infra/repository-permissions-updater/blob/e3abb0ea9cd32b895455e045297c96233023234d/src/main/java/io/jenkins/infra/repository_permissions_updater/hosting/MavenVerifier.java#L104-L107
