### ISSUE TITLE
Lacework Jenkins Plugin

### ISSUE THREAD

**Issue by alannix-lw** [jenkins-infra/repository-permissions-updater#2390]
### Repository URL

https://github.com/lacework-dev/jenkins-plugin

### New Repository Name

lacework-security-scanner-plugin

### Description

A Jenkins plugin for container assurance scans by Lacework

### GitHub users to have commit permission

@alannix-lw

### Jenkins project users to have release permission

alannix_lw

### Issue tracker

GitHub issues

**Comment by timja** [comment]
@Wadeck did you want to take a look?

**Comment by Wadeck** [comment]
@timja Superficial audit done, no need for a deeper look, thanks for the ping :-)

Welcome ;-)

**Comment by timja** [comment]
Non blocking comments:
1. As far as I know you don't want a hardcoded tag here: https://github.com/lacework-dev/jenkins-plugin/blob/ccffc125fd5b22a59ed5ac6ab5174f65926ad85f/pom.xml#L46 I think it should be `<tag>${scmTag}</tag>`
2. I would simplify the description here removing 'This plugin' https://github.com/lacework-dev/jenkins-plugin/blob/main/src/main/resources/index.jelly#L6
3. Icon is a png with a white background, this won't look good on any non default theme, I recommend you use an SVG instead https://github.com/lacework-dev/jenkins-plugin/blob/main/src/main/webapp/images/lacework.png
4. Use a logger not System.out https://github.com/lacework-dev/jenkins-plugin/blob/main/src/main/java/io/jenkins/plugins/laceworkscannerbuildstep/LaceworkScannerBuilder.java#L144
5. From what I can tell this requires docker on the controller https://github.com/lacework-dev/jenkins-plugin/blob/ccffc125fd5b22a59ed5ac6ab5174f65926ad85f/src/main/java/io/jenkins/plugins/laceworkscannerbuildstep/LaceworkScannerExecuter.java#L36 this likely won't work on quite a number of controllers. Especially mounting the socket seems strange.
