### ISSUE TITLE
Flakybot Artifacts Publisher

### ISSUE THREAD

**Issue by jainankit** [jenkins-infra/repository-permissions-updater#2430]
Removing the information as the plugin is reported invalid

**Comment by daniel-beck** [comment]
This plugin violates the terms of the MIT license that https://github.com/jenkinsci/http-post-plugin was published under (and which this plugin was basically directly copied from).

**Comment by daniel-beck** [comment]
Reopening, wrong button.

**Comment by Wadeck** [comment]
Closing this request as the previously linked repository is no longer available.
@jainankit Please open a new request with a public repository if you are still interested.
