### ISSUE TITLE
Host plugin in Jenkins marketplace

### ISSUE THREAD

**Issue by eyalperlm** [jenkins-infra/repository-permissions-updater#2452]
### Repository URL

https://github.com/QualiNext/sandbox-jenkins-plugin

### New Repository Name

torque-plugin

### Description

Torque is a SaaS Cloud Management Platform for DevOps. It provides Environments-as-a-Service, all the way from dev to production while allowing IT and project managers to govern the use of cloud resources from a single pane of glass. This plugin allows you to deploy Torque Sandboxes directly from TeamCity

### GitHub users to have commit permission

eyal.p@quali.com
reuven.b@quali.com
nehoray.h@quali.com

### Jenkins project users to have release permission

eyal.p@quali.com
reuven.b@quali.com
nehoray.h@quali.com

### Issue tracker

GitHub issues

**Comment by Wadeck** [comment]
Closing in favor of https://github.com/jenkins-infra/repository-permissions-updater/issues/2628.
