### ISSUE TITLE
Eggplant Runner Plugin

### ISSUE THREAD

**Issue by pohkheng2** [jenkins-infra/repository-permissions-updater#2458]
### Repository URL

https://github.com/TestPlant/eggplant-runner-jenkins

### New Repository Name

eggplant-runner-plugin

### Description

This plugin provides the capability for a user to run Eggplant DAI test configurations from a Jenkins pipeline.

### GitHub users to have commit permission

pohkheng2

### Jenkins project users to have release permission

pohkheng

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by Wadeck** [comment]
@timja superficial audit provided no interesting stuff to dig deeper, so 👍

**Comment by timja** [comment]
Non-blocking suggestions for improvement:

1. You README has `yaml` format for the pipeline but it should be groovy
2. You should use the plugin bom so you don't need to manage versions for each dependency: http://github.com/jenkinsci/bom
3. You are missing a `<url>` it appears to be commented out here: https://github.com/TestPlant/eggplant-runner-jenkins/blob/main/pom.xml#L107-L114
