### ISSUE TITLE
Fork `oidc-provider-plugin`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/repository-permissions-updater#2471]
### Repository URL

https://github.com/jglick/oidc-provider-plugin

### New Repository Name

oidc-provider-plugin

### Description

This plugin allows Jenkins to authenticate keylessly to systems which support OpenID Connect identity federation, by serving as an identity provider and offering JWT id tokens to builds. Specifically tested against both AWS and GCP. For example, Jenkins running on an arbitrary server with a public HTTPS URL can let builds assume an AWS role to work with an S3 bucket, without worrying about a static secret access key being leaked.

The Conjur plugin does something similar ([docs](https://github.com/jenkinsci/conjur-credentials-plugin#global-configuration-conjur-jwt-authentication)) but that is geared towards authenticating to Conjur specifically. Several other CI systems include analogous facilities, such as GitHub Actions ([docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)).

https://github.com/jenkinsci/oic-auth-plugin is totally unrelated—that allows Jenkins to be a “relying party” (rather than “identity provider”) as a security realm.

Includes minimal inline docs; more end-user docs coming soon, including working demos as soon as I sort out some technical issues in packaging them to be easy to run.

Ready for CD—please enable.

### GitHub users to have commit permission

@jglick
@escoem
@fcojfernandez

### Jenkins project users to have release permission

jglick
escoem
fcojfernandez

### Issue tracker

GitHub issues

**Comment by timja** [comment]
@Wadeck want to take a look at this?

**Comment by Wadeck** [comment]
@timja We have a complete audit expected in 2-3 weeks, so nothing needed at this point for this plugin 👍  thanks for the ping
