### ISSUE TITLE
Add systeminfo plugin which parses computer config description into a more human readable format

### ISSUE THREAD

**Issue by owenzhangzhengzhong** [jenkins-infra/repository-permissions-updater#2478]
### Repository URL

https://github.com/owenzhangzhengzhong/systeminfo-plugin

### New Repository Name

systeminfo-plugin

### Description

This plugin adds a System info page which formats the computer description into a new page, which allows for a better display of description (see readme). I couldn't find another plugin which does the same thing

### GitHub users to have commit permission

@owenzhangzhengzhong
@zhaeong

### Jenkins project users to have release permission

ozhang

### Issue tracker

Jira

**Comment by Wadeck** [comment]
No problem in terms of security ✔️ (late audit, sorry)
