### ISSUE TITLE
request to deploy my first plugin for jenkins

### ISSUE THREAD

**Issue by gabo89** [jenkins-infra/repository-permissions-updater#2490]
### Repository URL

https://github.com/gabo89/container-image-link

### New Repository Name

container-image-link-plugin

### Description

this plugin allow to add a  badge and a permalink in the ui with an url provided in the step, i find it very useful to use on the published container image or build image in jenkins, for example when i build my image with kaniko and publish to harbor i want to make a click in the ui and let jenkins me redirect me to the harbor url , so i compose the harbor url by myself and then i pass the harbor url to this plugin so it forward to the badge and the button then when i make click to the badge or tab it forward me to harbor, the same logic aplies to any other container registry , it was intented for harbor but i think it can be useful for all 

### GitHub users to have commit permission

@gabo89

### Jenkins project users to have release permission

gabocuadros

### Issue tracker

Jira

**Comment by gabo89** [comment]
doing a rapid check and comparing my ticket to other  i see that i am missing unit testing , implementing it while waiting

**Comment by gabo89** [comment]
added unit test successfully

**Comment by timja** [comment]
Hi

1. I would suggest something less generic than `newImageLink` for the step name, possibly `containerImageLink`?
2. It's preferable to use `svgs` over pngs for Icons.

No blockers though from me.

@Wadeck did you want to take a look?

**Comment by gabo89** [comment]
hello @timja thanks for the recommendation, i just aplied them to the repository , let me know if something else can be improve

**Comment by gabo89** [comment]
hello @Wadeck , do you have any news about this ticket ?

**Comment by gabo89** [comment]
hello @timja can you help me with attendance of this ticket ? :)

**Comment by timja** [comment]
Just awaiting confirmation from the security team, if no word by the end of the week I’ll host it then

**Comment by Wadeck** [comment]
Thanks for the ping. At first look there is a chance of XSS, deeper audit will be tracked as JENSEC-1811.

**Comment by gabo89** [comment]
hello @Wadeck @timja , do we have any news about this plugin :)?

**Comment by Kevin-CB** [comment]
Hi @gabo89,

We're able to perform a more complete audit on your plugin here are the feedback:

- A stored XSS in [HarborBadgeAction/badge.jelly#L3](https://github.com/gabo89/container-image-link/blob/02e04ba7e253bda52ce467eccb84b39d5d70ef76/src/main/resources/io/jenkins/plugins/functions/HarborBadgeAction/badge.jelly#L3), you're using a variable coming from the user directly in an attribute that can execute javascript (href).
If you use the payload `javascript:alert(1)` as url, it will raise an XSS when you click on the link.

Recommendation: 
Check for allowed protocols, and reject anything not specifically allowed as a start.

---

- Not a security vulnerability but please provide a short description of your plugin in [resources/index.jelly#L3](https://github.com/gabo89/container-image-link/blob/02e04ba7e253bda52ce467eccb84b39d5d70ef76/src/main/resources/index.jelly#L3), it will be displayed in the plugin manager.


We will let you correct the finding and ping us when you are done or if you have questions.

**Comment by gabo89** [comment]
hello @Kevin-CB  thanks for pointing that out, also another payload that cause the xss are `data:text/html;base64,PHNjcmlwdD5hbGVydCgiaGFja2VkIik7PC9zY3JpcHQ+` which is a box that says hacked , i am planning to just add http:// or https:// in short term to all request but as im discussing with friends that might not solve all issues ass well , i will try many alternatives and let you know when is fixed

**Comment by gabo89** [comment]
hello @Kevin-CB  i managed to solved the xss security error and also added a description in index.jelly  please have a look to see ifs its follow the security rules , i validate agaisnt a few url and seems to be working as expected from my side

**Comment by Kevin-CB** [comment]
Hi @gabo89,

I manually tested your correction and it looks OK! 

However I forgot to ask you to add the `rel="noopener noreferrer"` attribute to [HarborBadgeAction/badge.jelly#L3](https://github.com/gabo89/container-image-link/blob/02e04ba7e253bda52ce467eccb84b39d5d70ef76/src/main/resources/io/jenkins/plugins/functions/HarborBadgeAction/badge.jelly#L3) to avoid tabnapping vulnerability.

**Comment by gabo89** [comment]
hello @Kevin-CB  i just added the additional lines to make it  more secure, let me know if something else is missing,

**Comment by Kevin-CB** [comment]
Perfect, everything is good from a security point of view, we can continue the hosting process!

**Comment by gabo89** [comment]
thanks you all for the help!
