### ISSUE TITLE
conflict-aware-ondemand-retention-strategy-plugin

### ISSUE THREAD

**Issue by jimklimov** [jenkins-infra/repository-permissions-updater#2492]
### Repository URL

https://github.com/jimklimov/conflict-aware-ondemand-strategy-plugin

### New Repository Name

conflict-aware-ondemand-strategy-plugin

### Description

This plugin helps co-locate numerous build environments on resource constrained hosts, effectively sequentializing builds so they do not fail due to OOM killer or similar environmental failures.

This plugin started as PR https://github.com/jenkinsci/jenkins/pull/5764 against Jenkins Core, and thanks to Daniel Beck for extracting the changes as a viable stand-alone plugin and proposing the original name.

### GitHub users to have commit permission

@jimklimov

### Jenkins project users to have release permission

jimklimov

### Issue tracker

Jira

**Comment by timja** [comment]
Please update https://github.com/jimklimov/conflict-aware-ondemand-strategy-plugin/blob/main/src/main/resources/index.jelly#L3 before publishing
