### ISSUE TITLE
Apimap Plugin

### ISSUE THREAD

**Issue by msulland** [jenkins-infra/repository-permissions-updater#2504]
### Repository URL

https://github.com/apimap/plugin-jenkins

### New Repository Name

apimap-plugin

### Description

Why is this project useful? Lost track of all the API functionality provided inside your organization? Don't want to be tied to an API proxy or management solution? The Apimap.io project uploads, indexes and enables discoverability of all your organizations APIs. We care about the source code, removing the limitation of where the API is hosted and how your network is constructed.

### GitHub users to have commit permission

@msulland

### Jenkins project users to have release permission

msulland

### Issue tracker

GitHub issues

**Comment by Wadeck** [comment]
Superficial security audit:
- [doTestConnection](https://github.com/apimap/plugin-jenkins/blob/c3033cd2a39e26f158f93248940d5bceb2978e9b/src/main/java/io/apimap/plugin/jenkins/ApiMap.java#L108-L125) must be protected, missing CSRF and missing permission check. Recommended documentation: https://www.jenkins.io/doc/developer/security/form-validation/
- I imagine that the `token` is something confidential, so [PublishStep/config.jelly#L10](https://github.com/apimap/plugin-jenkins/blob/main/src/main/resources/io/apimap/plugin/jenkins/PublishStep/config.jelly#L10) should be changed to `f:password` and [PublishStep.java#L47](https://github.com/apimap/plugin-jenkins/blob/c3033cd2a39e26f158f93248940d5bceb2978e9b/src/main/java/io/apimap/plugin/jenkins/step/PublishStep.java#L47) from String to `hudson.util.Secret`. Recommended documentation: https://www.jenkins.io/doc/developer/security/secrets/

**Comment by msulland** [comment]
@Wadeck ?

**Comment by msulland** [comment]
@Wadeck I have added a check to enable the feature only for administrators, and added a short test to see if the user has any arguments in the URL (just to help people to use only the root resource). Does this help?

**Comment by Wadeck** [comment]
@msulland the permission check is good, thanks. Now the method is still vulnerable to CSRF, you have to add the `@RequirePOST` or `@POST` annotation, and ensure the related UI is sending POST requests.

Related documentation: https://www.jenkins.io/doc/developer/security/form-validation/#protecting-from-csrf

**Comment by msulland** [comment]
@Wadeck Added @POST

**Comment by Wadeck** [comment]
If everything reported was changed 👍

**Comment by msulland** [comment]
@Wadeck I deleted the test button instead. Just removed the functionallity

**Comment by timja** [comment]
@Wadeck to confirm you're happy?

**Comment by Wadeck** [comment]
@timja Exactly 👍
