### ISSUE TITLE
Lightstep Incident Response Plugin

### ISSUE THREAD

**Issue by sn-priya-jagyasi** [jenkins-infra/repository-permissions-updater#2513]
### Repository URL

https://code.devsnc.com/dev/air-external-integration/tree/master/plugins/observability/jenkins/lightstep-incident-response

### New Repository Name

lightstep-incident-response-plugin

### Description

- We want to host a lightstep-incident-response plugin to integrate Jenkins with Lightstep Incident Response(LIR) application.
- It will enable post-build action namely "Send alerts to Lightstep Incident Response" which when selected gives options to select build status for alert creation on LIR.
- Whenever a build is completed for a Freestyle job, it will post the result to the Lightstep Incident Response application to create alerts.

### GitHub users to have commit permission

@ashutosh-SNow
@rohini.ramakrishnappa
@phanibh.kanakamedala
@kirankumar-nunna
@priya-jagyasi011
@ashu248

### Jenkins project users to have release permission

@ashutosh-SNow
@rohini.ramakrishnappa
@phanibh.kanakamedala
@kirankumar-nunna
@priya-jagyasi011
@ashu248

### Issue tracker

Jira

**Comment by Wadeck** [comment]
@sn-priya-jagyasi FYI your repository is not accessible. Is it related to https://github.com/ServiceNow/lightstep-incident-response ? (which is an archive)

If it's that repository, the superficial security audit was sufficient, nothing to report. If it's not, please provide a public link, in GitHub.

**Comment by NotMyFault** [comment]
Hey @sn-priya-jagyasi,

to process this hosting request, please
- clarify Wadeck's question, whether https://github.com/ServiceNow/lightstep-incident-response is the repository you want to host.
- update the user mentions of the GitHub users you want to have permission on the hosted repository. Only one mention is a valid user.

Thanks!

**Comment by NotMyFault** [comment]
@sn-priya-jagyasi If you are still interested in continuing with this hosting request, please address the outstanding concerns and re-open the request.

Thanks!
