### ISSUE TITLE
RPU builds failing on trusted.ci for the `Archive` step due to missing `az`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/repository-permissions-updater#2520]
### Reproduction steps

I've been careless in https://github.com/jenkins-infra/pipeline-library/pull/348 , being only focused on infra-reports, and forgot to check the known usages of the shared library `PublishReportsStepTests`.

It results in the RPU builds failing since the 28th of April during the last "archive" stage, with the error `az: not found` (Azure Command line not found).

Incoming PR, but I though it was important to let you folks know.

### Expected Results

Builds of RPU on trusted.ci.jenkins.io should not fail.

### Actual Results

error `az: not found` on the trusted.ci builds of RPU

**Comment by timja** [comment]
Thanks, looks like it won't cause any issue, appears to be mostly a debugging aid right at the end of the pipeline

**Comment by dduportal** [comment]
In order to fix this issue, we have to:

- Ensure that azure-cli is installed in the VM agent templates:
  - [x] PR to add the tool on all platforms + tracking version: https://github.com/jenkins-infra/packer-images/pull/216
  - [ ] PR to deploy new template on ci.j and trusted.j
- [ ] Check if the CLI call works with latest `azure-cli` version or fix it otherwise

**Comment by dduportal** [comment]
fixed: closing issue
