### ISSUE TITLE
Missing Permissions to publish plugin

### ISSUE THREAD

**Issue by lineville** [jenkins-infra/repository-permissions-updater#2531]
### Reproduction steps

I have recently had my paginated-builds-plugin [hosting request](https://github.com/jenkins-infra/repository-permissions-updater/issues/2515) approved. I am attempting to publish the plugin now via GitHub but am receiving a 403 permission error when pushing up a new branch to this repo. I need to open up a PR in order to add `cd: enabled: true` to [this file](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-paginated-builds.yml) but am blocked by the permission issue. I have accepted the invitation to join the jenkinci org, and successfully logged into Artifactory and see my username `lineville` under the list of developers.

### Expected Results

I expected to be able to push to this repo, but cannot. I believe I have been given access to jenkinsci but not jenkins-infra

### Actual Results

`remote: Permission to jenkins-infra/repository-permissions-updater.git denied to lineville.
fatal: unable to access 'https://github.com/jenkins-infra/repository-permissions-updater.git/': The requested URL returned error: 403`

### Anything else?

If you could please give me access to push to this repo, or open up the PR I've described on my behalf that would be great!

**Comment by daniel-beck** [comment]
You will not be granted permissions to push to this repo. Use pull requests from forks.
