### ISSUE TITLE
Port scanner plugin

### ISSUE THREAD

**Issue by dtbaum** [jenkins-infra/repository-permissions-updater#2536]
### Repository URL

https://github.com/dtbaum/portscanner

### New Repository Name

portscanner-plugin

### Description

 This plugin, developed in pure Java, detects:

- Open ports 
- Supported TLS ciphers 
- Cipher strength of detected ciphers via https://ciphersuite.info/.

I wasn't able to find a pugin with similar functionality.

### GitHub users to have commit permission

@dtbaum 

### Jenkins project users to have release permission

tbaum

### Issue tracker

GitHub issues

**Comment by timja** [comment]
is dim the right GitHub user? (not you)

**Comment by timja** [comment]
cc @Wadeck

**Comment by Wadeck** [comment]
Superficial audit => not needed to have a full audit.

- [OpenPort.java#L84-L89](https://github.com/dtbaum/portscanner/blob/fea700aefd8562153a91b260e00cc5ab3e1a888b/src/main/java/io/jenkins/plugins/portscanner/OpenPort.java#L84-L89) those settings change the configuration of the Controller. I would ask you to do your system modification in the agent directly instead, to not have a permanent impact on the Controller. 
Perhaps that `MasterToSlaveCallable` or `Launcher#launch` could help for that purpose.

**Comment by dtbaum** [comment]
Hello @Wadeck, 
You a right, I have fixed it as recommended, by using MasterToSlaveCallable.

**Comment by timja** [comment]
Please change your `MasterToSlaveCallable` to a static class rather than an anonymous one.
There's serialization issues with anonymous ones.

example: https://github.com/alecharp/jenkins/blob/4184ca735ad6fb82db2cf2319deb030e7759a8e2/core/src/main/java/hudson/model/Computer.java#L1316

**Comment by timja** [comment]
@Wadeck did you want to re-check?

**Comment by Wadeck** [comment]
@timja No that's good 👍

**Comment by dtbaum** [comment]
@timja  I have replaced an anonymous class by a static one, as recommended. Thank you for your support!
