### ISSUE TITLE
Worksoft Continuous Testing Manager Plugin

### ISSUE THREAD

**Issue by raleigh-rinehart** [jenkins-infra/repository-permissions-updater#2547]
### Repository URL

https://github.com/Worksoft/worksoft-ctm-plugin

### New Repository Name

worksoft-ctm-plugin

### Description

This is the official Worksoft Supported Plugin for CTM.
The plugin adds build steps for interacting with a Worksoft's Continuous Testing Manager to run your Certify processes or ALM labs.

### GitHub users to have commit permission

@glenpgillman
@raleigh-rinehart 

### Jenkins project users to have release permission

glenpgillman
rrinehart

### Issue tracker

Jira

**Comment by glenpgillman** [comment]
FYI - we've tried our repository multiple times.   It is valid.   We've even renamed it to see if we can resolve the issue.   The bot still seems to be caching the old repository name.  Please advise on what we are missing

**Comment by timja** [comment]
Aware not sure what's going on

**Comment by timja** [comment]
You could try create it as a new repo? I'm wondering if the API is replying weirdly because of the rename / the script doesn't handle

**Comment by glenpgillman** [comment]
I tried that and a few other things.  No improvement.

Is there anything you can look into on your side ?

Thank you

**Comment by timja** [comment]
I mean creating a new GitHub repository as that would likely work (even just creating it in a personal account).

Possibly but I don't have the time to look into it now.
I checked the logs in https://github.com/jenkins-infra/repository-permissions-updater/runs/6465637479?check_suite_focus=true and couldn't see anything interesting.

you can run the scripts locally yourself and see if you can find the issue.

**Comment by glenpgillman** [comment]
Thank you for your help.  I understand your time is limited.  

From what we've seen, the issue is with the target repo worksoft-ctm-plugin.   It for some reason is failing to create the destination repo in jenkinsci org with the name we specified.   I don't think there is anything we can do with our permissions level to identify why the destination repo is not being created by the bot.   

Thank you

**Comment by timja** [comment]
the bot doesn't create the repo it just tries to validate it doesn't exist

**Comment by timja** [comment]
That will be created after I approve the request but I can't approve it till the checks pass

**Comment by raleigh-rinehart** [comment]
Closing this issue as we can't seem to determine what the bot is having issues with.  
Will create a new issue.
@glenpgillman FYI
