### ISSUE TITLE
Worksoft Continuous Testing Manager Plugin

### ISSUE THREAD

**Issue by raleigh-rinehart** [jenkins-infra/repository-permissions-updater#2550]
### Repository URL

https://github.com/Worksoft/worksoft-ctm-plugin

### New Repository Name

ws-ctm-plugin

### Description

This is the official Worksoft Supported Plugin for CTM.
The plugin adds build steps for interacting with a Worksoft's Continuous Testing Manager to run your Certify processes or ALM labs.

### GitHub users to have commit permission

@raleigh-rinehart
@glenpgillman

### Jenkins project users to have release permission

rrinehart
glenpgillman

### Issue tracker

Jira

**Comment by glenpgillman** [comment]
why is the hosting checker trying to validate a destination git repo that doesn't exist yet?   I'm confused.   Of course 'ws-ctm-plugin' will not have been created as a destination jenkins CI repo until this issue is approved.  Are we missing something ?

**Comment by raleigh-rinehart** [comment]
At this point we are unsure what the problem is nor how to fix it to proceed.

The bot seems to be complaining about the destination repo `ws-ctm-plugin` not being valid.  Which of course it is not as it has not been created yet.  A search in Jenkins CI GitHub org for other repositories with the same name turns up empty, so that is not the issue either. 
Review the bot's actions (https://github.com/jenkins-infra/repository-permissions-updater/runs/6477610395?check_suite_focus=true) turns up nothing that points to the problem

@glenpgillman FYI

**Comment by raleigh-rinehart** [comment]
@timja It looks like there might be a bug in `GradleVerifier.java`
Lines 70 & 71 seem to have the `from` repo and `to` repo swapped:
```java
   forkTo = issue.getRepositoryUrl();
   forkFrom = issue.getNewRepoName();
```

**Comment by timja** [comment]
Ha thanks, makes sense, this may be the first gradle based plugin since this was introduced

**Comment by timja** [comment]
Hello from your friendly Jenkins Hosting Checker

It appears you have some issues with your hosting request. Please see the list below and correct all issues marked Required. Your hosting request will not be approved until these issues are corrected. Issues marked with Warning or Info are just recommendations and will not stall the hosting process.
* :no_entry: Required: Repository URL 'ws-ctm-plugin' is not a valid GitHub repository (check that you do not have .git at the end, GitHub API doesn't support this).

You can re-trigger a check by editing your hosting request or by commenting `/hosting re-check`

**Comment by timja** [comment]
Hello from your friendly Jenkins Hosting Checker

It appears you have some issues with your hosting request. Please see the list below and correct all issues marked Required. Your hosting request will not be approved until these issues are corrected. Issues marked with Warning or Info are just recommendations and will not stall the hosting process.
* :no_entry: Required: Your build.gradle file is missing the `jenkinsVersion` item.
* :no_entry: Required: The `shortName` from the build.gradle (worksoft-ctm) is incorrect, it should be 'ws-ctm' ('New Repository Name' field with "-plugin" removed)
* :no_entry: Required: The `group` from the build.gradle should be `io.jenkins.plugins` instead of `org.jenkins-ci.plugins`
* :no_entry: Required: Please specify a license in your build.gradle file using the `licenses` closure. See https://github.com/jenkinsci/gradle-jpi-plugin#configuration for an example.
* :information_source: Info: The `jenkinsVersion` value from your build.gradle seems to be a variable, we cannot verify the `jenkinsVersion` in this case, please make sure it is set to at least `2.277.1`

You can re-trigger a check by editing your hosting request or by commenting `/hosting re-check`

**Comment by timja** [comment]
cc @Wadeck

**Comment by yaroslavafenkin** [comment]
@timja JenSec will have a deeper look at this one

**Comment by glenpgillman** [comment]
any information you can pass along about this ?  we appreciate all your help

**Comment by Wadeck** [comment]
@glenpgillman The security needs to do an audit on this hosting request as Yaroslav mentioned. We have currently several audit in progress, so no ETA at the moment.

**Comment by glenpgillman** [comment]
Thank for the heads up.   Is this the only remaining item on this ?    Can you provide a number in the queue and where we sit in that queue ?

Thank you

**Comment by yaroslavafenkin** [comment]
Hey @glenpgillman,

We were able to perform a deeper audit and here's some feedback for you:

* SSRF if attacker knows valid credentialId in [ExecuteRequestCTMConfig.java#L137](https://github.com/Worksoft/worksoft-ctm-plugin/blob/b05ba927885d3d0e171cd8bc0b2d53814a55d262/src/main/java/com/worksoft/jenkinsci/plugins/ctm/ExecuteRequestCTMConfig.java#L137) and in [ExecuteSuite.java#L64](https://github.com/Worksoft/worksoft-ctm-plugin/blob/b05ba927885d3d0e171cd8bc0b2d53814a55d262/src/main/java/com/worksoft/jenkinsci/plugins/ctm/ExecuteSuite.java#L64)
URLs to invoke those methods are respectively: `<JENKINS_URL>/descriptorByName/com.worksoft.jenkinsci.plugins.ctm.ExecuteRequestCTMConfig/testConnection?url=<url>&credentials=<validCredentialId>` and `<JENKINS_URL>/descriptorByName/com.worksoft.jenkinsci.plugins.ctm.ExecuteSuite/fillNameItems?url=<url>&credentials=<validCredentialId>`
Both calls result in requests being sent by Jenkins to the provided URL given `credentialId` is valid.

Recommendation: add a permission check and CSRF protection. Refer to https://www.jenkins.io/doc/developer/security/form-validation/#implementing-form-validation for details.

Please address our findings and ping us when you're done or if you have any questions.

**Comment by timja** [comment]
Hi

Why have you got an l:header and css in the index.jelly?

https://github.com/Worksoft/worksoft-ctm-plugin/blob/master/src/main/resources/index.jelly#L11-L19

Normally this is pretty much just plain text and its for displaying in the plugin manager inside of Jenkins.

**Comment by yaroslavafenkin** [comment]
> in ExecuteRequestCTMConfig a couple lines below L137 we have this validation for the credentials:
> 
> ```
>   StandardUsernamePasswordCredentials creds = lookupCredentials(url, credentials);
>   if (creds == null) {
>     return FormValidation.error("Credentials lookup error!");
>   }
> ```
> 
> I reviewed the documentation, what part of this is not sufficient ? I appreciate your help with this.

@glenpgillman, it's not the part you mentioned in particular.
Currently low privileged user (say with Overall/Read permissions) can invoke either of those methods by requesting the URL I mentioned in previous comment, which should not be possible. What's missing is a check for valid permissions and either `@POST` or `@RequirePOST` annotation to prevent CSRF attack.

Similarly as you're checking permission in a method few lines above: https://github.com/Worksoft/worksoft-ctm-plugin/blob/b05ba927885d3d0e171cd8bc0b2d53814a55d262/src/main/java/com/worksoft/jenkinsci/plugins/ctm/ExecuteRequestCTMConfig.java#L119
You can use either `Jenkins.checkPermission` or `Jenkins.hasPermission` for that.

Please let us know if you have any further questions.

**Comment by glenpgillman** [comment]
@yaroslavafenkin @timja Thank you very much for your help.   We have pushed the latest changes.  Please review when you have a moment.  Thanks.

**Comment by yaroslavafenkin** [comment]
@glenpgillman,

* [ExecuteRequestCTMConfig.java#L137](https://github.com/Worksoft/worksoft-ctm-plugin/blob/master/src/main/java/com/worksoft/jenkinsci/plugins/ctm/ExecuteRequestCTMConfig.java#L137) is fine in terms of permissions, but also needs CSRF protection.
* [ExecuteSuite.java#L65](https://github.com/Worksoft/worksoft-ctm-plugin/blob/master/src/main/java/com/worksoft/jenkinsci/plugins/ctm/ExecuteSuite.java#L65) is not okay, `Jenkins.READ` permission is implicit. As far as I can tell that method is invoked from job configuration page, so `Job.CONFIGURE` permission should be ok there. And it's also still missing CSRF protection.

Reference documentation: https://www.jenkins.io/doc/developer/security/form-validation/#protecting-from-csrf

**Comment by glenpgillman** [comment]
@yaroslavafenkin    Thank you for all your help.  I believe I've made the necessary changes.

**Comment by yaroslavafenkin** [comment]
Looks good to me now 👍
