### ISSUE TITLE
Feishu 

### ISSUE THREAD

**Issue by cafedeflore** [jenkins-infra/repository-permissions-updater#2554]
### Repository URL

https://github.com/cafedeflore/feishu-plugin

### New Repository Name

feishu-plugin

### Description

Send Feishu robot message.

### GitHub users to have commit permission

@cafedeflore 

### Jenkins project users to have release permission

cafedeflore

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by yaroslavafenkin** [comment]
@timja JenSec will have a deeper look at this one

**Comment by Kevin-CB** [comment]
Hello @cafedeflore, 

We were able to perform a more complete audit on your plugin and no vulnerability came out, thank you for your patience. 
We can continue the hosting process.

**Comment by timja** [comment]
There's a few packaging issues which need taking care of before we host this:

1. `okhttp` dependency should be changed to use the [okhttp-api-plugin](https://plugins.jenkins.io/okhttp-api/#dependencies
)
2. `slf4j-api` dependency should be removed as it's packaged in Jenkins core, if something else is trying to pull it in exclude it
3. `jaxb-api` should be changed to the [jaxb plugin](https://plugins.jenkins.io/jaxb/#dependencies)

Jenkins developers create API plugins for popular libraries. See [Using library wrapper plugins](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#using-library-wrapper-plugins) for more information.

----

All looks good apart from that

**Comment by NotMyFault** [comment]
Hey @cafedeflore,

could you address the findings from timja please? https://github.com/jenkins-infra/repository-permissions-updater/issues/2554#issuecomment-1140524935
This would help to process the request.

Thanks!

**Comment by NotMyFault** [comment]
@cafedeflore If you are still interested in continuing with this hosting request, please address the outstanding concerns and re-open the request.

Thanks!
