### ISSUE TITLE
Jenkins Job Tag Plugin

### ISSUE THREAD

**Issue by nistal97** [jenkins-infra/repository-permissions-updater#2568]
### Repository URL

https://github.com/nistal97/jobtag-plugin

### New Repository Name

jobtag-plugin

### Description

[jobtag plugin](https://github.com/nistal97/jobtag-plugin) is one simple plugin to help user to add multiple tags to job configuration, and display in list view.

### Purpose

- If jobs numbers grows, users are difficult to identify the purpose of each job. Job name would be confusing if naming convension is not clear. However, adding multiple tags for job could help easily identify the purpose of this job.
- This plugin provides a simple way to help categorize jobs in same purpose, group or pipeline. eg, job "staging_deploy_job" could have tag"STAGING" ,"DEPLOY_JOB" , "GOLDEN_RELEASE_PIPELINE"
- Integration: Other systems could get job list based on tag query, provided sample script

### GitHub users to have commit permission

@nistal97

### Jenkins project users to have release permission

nistal97

### Issue tracker

GitHub issues

**Comment by timja** [comment]
I wonder if labels are too similar to Jenkins's existing labels for selecting where a job should run?
Would tags be more appropriate?

**Comment by timja** [comment]
You don't need to prefix border-radius:
https://github.com/nistal97/joblabel-plugin/blob/f35434c6cf98320174fcb672c2ab40c542004120/src/main/resources/io/jenkins/plugins/joblabel/JobLabelColumn/column.jelly#L10

----

cc @Wadeck I've had a check over and don't see anything suspicious but did you want to sanity check it?

**Comment by Wadeck** [comment]
Quick check => nothing suspicious as well 👍

**Comment by nistal97** [comment]
thanks @timja and @Wadeck , are we good now or anything needs to change?

**Comment by timja** [comment]
I’m concerned that label is not an appropriate name as Jenkins already has a label concept (and I suggested tag as an alternative)

anyone else have a view on it?
(Tagging some people who may be interested feel free to ignore)
@basil @daniel-beck @markewaite @halkeye @jglick

**Comment by halkeye** [comment]
I second the tag idea. Goes well with SCM too. But not a blocker by me

**Comment by nistal97** [comment]
@timja @halkeye   Agreed tag should be a better name. I got everything changed to "tag" and fully tested.
