### ISSUE TITLE
Quali Torque Plugin

### ISSUE THREAD

**Issue by sasha-quali** [jenkins-infra/repository-permissions-updater#2628]
### Repository URL

https://github.com/QualiTorque/sandbox-jenkins-plugin

### New Repository Name

quali-torque-plugin

### Description

The Torque Jenkins Plugin provides an easy way to consume Torque sandboxes through Jenkins for a variety of use cases. The plugin allows you to build jobs that create on-demand sandboxes in Torque based on pre-defined blueprints.

### GitHub users to have commit permission

@ddovbii
@kalsky
@sasha-quali
@AlexSuprun

### Jenkins project users to have release permission

sasha_quali
quali_integrations

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by yaroslavafenkin** [comment]
CERT will have a deeper look at this one.

**Comment by yaroslavafenkin** [comment]
@sasha-quali,

* [Config.java#L37](https://github.com/QualiTorque/sandbox-jenkins-plugin/blob/7cc16ffda5e58bc454f940a44ad872c6194cfcc7/src/main/java/org/jenkinsci/plugins/torque/Config.java#L37) declares a token field of type String. This would result in the token being stored in plain text on disk which is considered insecure.
Our recommendation is to use Secret for fields that store sensitive data. https://www.jenkins.io/doc/developer/security/secrets/
* [jenkins-whitelist#L6](https://github.com/QualiTorque/sandbox-jenkins-plugin/blob/be3fbe576e9a35d09ffa67be0e94cfc74c868c9e/src/main/resources/org/jenkinsci/plugins/torque/whitelists/jenkins-whitelist#L6), this is such a terrible idea it's explicitly listed on the script-security blacklist as something that should never be approved: [scriptsecurity/sandbox/whitelists/blacklist#L8](https://github.com/jenkinsci/script-security-plugin/blob/4bd517d6dbf0926c3d506005e11187006d8f556f/src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist#L8)
Whitelists are system-wide, so installing the plugin would poke a pretty big hole in the script security sandbox for the entire instance. Is there any specific reason you have it in the whitelist?

**Comment by sasha-quali** [comment]
Please check the new commits that fix the issues

**Comment by Wadeck** [comment]
Sending notif to the security team: /audit-security-review

**Comment by Wadeck** [comment]
Sending notif to the security team: /audit-review

**Comment by Wadeck** [comment]
Sending notif to the security team: /audit-review

**Comment by yaroslavafenkin** [comment]
Security concerns mentioned in https://github.com/jenkins-infra/repository-permissions-updater/issues/2628#issuecomment-1190123263 have been addressed. No other remarks from me.

**Comment by daniel-beck** [comment]
> https://github.com/QualiTorque/sandbox-jenkins-plugin/blob/be3fbe576e9a35d09ffa67be0e94cfc74c868c9e/src/main/java/org/jenkinsci/plugins/torque/PluginConstants.java#L7-L13 these should probably be made less generic, given that "sandbox" means something very different in the context of Jenkins Pipeline.

While this is not a security finding I recommend these be changed, and that reviewers not accept this plugin while it has such generic and misleading symbols.

**Comment by Wadeck** [comment]
After Yaroslav's comment => /audit-ok

**Comment by sasha-quali** [comment]
> > https://github.com/QualiTorque/sandbox-jenkins-plugin/blob/be3fbe576e9a35d09ffa67be0e94cfc74c868c9e/src/main/java/org/jenkinsci/plugins/torque/PluginConstants.java#L7-L13 these should probably be made less generic, given that "sandbox" means something very different in the context of Jenkins Pipeline.
> 
> While this is not a security finding I recommend these be changed, and that reviewers not accept this plugin while it has such generic and misleading symbols.

Is it acceptable to just add a plugin name into that constant?

**Comment by daniel-beck** [comment]
A disambiguating prefix like that, resulting in symbols like `qualitorqueSandbox` or similar would be fine IMO 👍

**Comment by sasha-quali** [comment]
Please review the latest code
