### ISSUE TITLE
Host: bmc-change-manager-imstm-plugin

### ISSUE THREAD

**Issue by mcohen11** [jenkins-infra/repository-permissions-updater#2633]
### Repository URL

https://github.com/mcohen11/bmc-change-manager-imstm-plugin

### New Repository Name

bmc-change-manager-imstm-plugin

### Description

New Jenkins plug-in that allows customers assimilate BMC AMI Change Manager for IMS TM capabilities in their Dev/Ops processes. It takes advantage of BMC AMI Change Manager for IMS TM functionality to dynamically activate changes to IMS objects.

### GitHub users to have commit permission

@mcohen

### Jenkins project users to have release permission

mcohen

### Issue tracker

GitHub issues

**Comment by mcohen11** [comment]
I'm connected both to Jira and Artifactory with username: mcohen and it keeps failing...
<img width="950" alt="image" src="https://user-images.githubusercontent.com/93242861/177396407-12ed0245-19f4-44e8-a648-4b83400a3d9c.png">

**Comment by daniel-beck** [comment]
Try now.

**Comment by timja** [comment]
The Jenkins project account has an @ prepended when it’s not a GitHub account, that was probably the issue

**Comment by timja** [comment]
cc @Wadeck

**Comment by mcohen11** [comment]
Any progress?

**Comment by yaroslavafenkin** [comment]
Hi @mcohen11,

We've performed a deeper audit and back with some feedback.
[TrustAllHostNameVerifier.java](https://github.com/mcohen11/bmc-change-manager-imstm-plugin/blob/abe387fb290414ae088d170ce1dcb3c394205331/src/main/java/com/bmc/ims/TrustAllHostNameVerifier.java) raises some concerns, but I haven't found any usages of it. Can you confirm this is not used anywhere?

Dependency scan has identified 2 issues in org.json:json:
- https://advisory.checkmarx.net/advisory/vulnerability/Cx08fcacc9-cb99/
- https://advisory.checkmarx.net/advisory/vulnerability/Cxdb5a1032-eda2/

I'm not sure if your plugin is affected. It can be left as is if you say it's not affected. Upgrading to 20200518 or above is known to remediate those issues if plugin is affected.

**Comment by mcohen11** [comment]
- TrustAllHostNameVerifier class was removed.

- I've upgraded the JSON packages's version.

Thanks,
Marit.

**Comment by timja** [comment]
Non-blocking issues:

- `pom.xml` uses inconsistent formatting between tabs and spaces making it look weird when viewing
- There are a number of broken screenshots in the README: https://github.com/mcohen11/bmc-change-manager-imstm-plugin#screenshots-
- There are commented out imports for some reason: https://github.com/mcohen11/bmc-change-manager-imstm-plugin/blob/master/src/main/java/com/bmc/ims/JCLService.java


🚫  Blocking issues:

- [JCLService](https://github.com/mcohen11/bmc-change-manager-imstm-plugin/blob/master/src/main/java/com/bmc/ims/JCLService.java) is not licensed under an open source license

**Comment by mcohen11** [comment]
Done.

Regarding the screenshots: I used the path that will be relevant once the plugin is published:
https://github.com/jenkinsci/bmc-change-manager-imstm-plugin/blob/main/src/main/webapp/images/bmc_build_step.jpg)

**Comment by mcohen11** [comment]
Thanks!
