### ISSUE TITLE
Enhanced Metrics Plugin - Hosting Request

### ISSUE THREAD

**Issue by aytuncbeken** [jenkins-infra/repository-permissions-updater#2657]
### Repository URL

https://github.com/aytuncbeken/enhanced-metrics-plugin

### New Repository Name

enhanced-metrics-plugin

### Description

Enables detailed metrics for Jobs/Nodes/Users

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by yaroslavafenkin** [comment]
CERT had a superficial look, and everything looks fine. We can proceed with the hosting.
