### ISSUE TITLE
VkNotifier

### ISSUE THREAD

**Issue by Spliterash** [jenkins-infra/repository-permissions-updater#2665]
### Repository URL

https://github.com/Spliterash/jenkins-vk-notifier

### New Repository Name

vk-notifier-plugin

### Description

The plugin allows you to send messages to the Russian social network [vk.com](https://vk.com)
Supports Post-build Actions and pipeline

### GitHub users to have commit permission

@Spliterash

### Jenkins project users to have release permission

Spliterash

### Issue tracker

GitHub issues

**Comment by timja** [comment]
cc @Wadeck

**Comment by daniel-beck** [comment]
API key should be stored as a `Secret` (including getter/setter types) and displayed using `f:password`.

https://github.com/Spliterash/jenkins-vk-notifier/blob/af7cb285bb4bcb9ce8b23ca7b526cfce68af50a4/src/main/java/ru/spliterash/jenkinsVkNotifier/jenkins/defaultJob/VkNotifierPostAction.java#L69
https://github.com/Spliterash/jenkins-vk-notifier/blob/af7cb285bb4bcb9ce8b23ca7b526cfce68af50a4/src/main/resources/ru/spliterash/jenkinsVkNotifier/jenkins/defaultJob/VkNotifierPostAction/global.jelly#L5

See https://www.jenkins.io/doc/developer/security/secrets/

**Comment by yaroslavafenkin** [comment]
After changes mentioned in https://github.com/jenkins-infra/repository-permissions-updater/issues/2665#issuecomment-1191916355 it looks alright to me, no other remarks.
