### ISSUE TITLE
Host the Gradle JTE Plugin

### ISSUE THREAD

**Issue by steven-terrana** [jenkins-infra/repository-permissions-updater#2670]
### Repository URL

https://github.com/steven-terrana/gradle-jte-plugin

### New Repository Name

gradle-jte-plugin

### Description

This repository is a Gradle Plugin related to the [Templating Engine Plugin](https://github.com/jenkinsci/templating-engine-plugin). 

The Templating Engine Plugin allows users to configure pipeline libraries. 

This Gradle Plugin extends the [Gradle JPI Plugin](https://github.com/jenkinsci/gradle-jpi-plugin) to make it easy for library authors to package their libraries as a stand-alone Jenkins plugin.

This would additionally require release permissions to the `org.jenkins-ci.tools` group on the [Gradle Plugin Portal](https://plugins.gradle.org).

### GitHub users to have commit permission

@steven-terrana

### Jenkins project users to have release permission

sterrana

### Issue tracker

GitHub issues

**Comment by steven-terrana** [comment]
Hey there friendly neighborhood Jenkins Hosting Checker..

This isn't a Jenkins Plugin, but a Gradle Plugin.

So i think we can disregard these checks in this instance.

**Comment by timja** [comment]
> This would additionally require release permissions to the org.jenkins-ci.tools group on the [Gradle Plugin Portal](https://plugins.gradle.org/).

cc @sghill 

This could also be an opportunity to use `io.jenkins.tools` instead as the other group id is a legacy one

----

@Wadeck did you want to check this for security?

**Comment by Wadeck** [comment]
Yeah it will be interesting to still have a look :) It's part of the supply chain attack surface.

**Comment by sghill** [comment]
@timja Thanks for the ping. I think I'm going to pass on moving the groupId of the gradle-jpi-plugin for now.

Great idea for a first publication, but an existing one won't conflict resolve with its older versions by default. Ends up creating duplicate classes on the classpath without special rules.

**Comment by timja** [comment]
Hey Steve, the ping was more for how can Steven publish under the existing group ID, or should he just publish under a new one

**Comment by sghill** [comment]
Ah, he'll need an account for the Gradle Plugin Portal and it will have to be approved by Gradle ([guide](https://plugins.gradle.org/docs/publish-plugin)).

Either group will work I think. Main constraint is that the short name is unique. I'd choose the io group since it's newer.

**Comment by steven-terrana** [comment]
I tried publishing to `org.jenkins-ci.tools` and got a permissions error. 

I'm happy to try publishing to the new `io.jenkins.tools` group but i believe the repository will have to be forked to the `jenkinsci` organization first.

**Comment by steven-terrana** [comment]
sorry for the double ping - trying to make sure i'm clear on next steps.

should i proceed with attempting to publish to the `io.jenkins.tools` group linked to my current git repository or hold until we've done a security assessment and forked the repository to `jenkinsci`?

**Comment by timja** [comment]
hold until security assessment but you can update the group id now

**Comment by dwnusbaum** [comment]
@yaroslavafenkin and I reviewed this and it looks fine from a security standpoint.

**Comment by steven-terrana** [comment]
hey @timja,

When trying to publish to the Gradle plugin portal, they're looking for us to prove ownership of the `jenkins-ci.io` domain..

> Please prove ownership of the "[jenkins-ci.io](http://jenkins-ci.io/)" domain by adding a TXT record with value "gradle-verification=QH6WADZ8BZPQXNH3VBM2TXX288R7P" to your DNS.

Any suggestions on how we can proceed here?

**Comment by timja** [comment]
jenkins-ci.io is not a domain.

the domain is io.jenkins or io.jenkins.tools
