### ISSUE TITLE
CD token generation fails for long repo names

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/repository-permissions-updater#2681]
There seems to be an undocumented length limit for the name of the virtual user created for admin tokens, or some other string that includes this value. @dwnusbaum reports that no token for `apache-httpcomponents-client-4-api` is being created, and the log confirms:

```
INFO	java_util_logging_Logger$log$1#call: Generating token with request payload: username=CD-for-jenkinsci__apache-httpcomponents-client-4-api-plugin&scope=member-of-groups%3Areaders%2Cgeneratedv2-cd-jenkinsci_apache-httpcomponents-client-_7ae8af7&expires_in=14400
INFO	o.c.g.r.c.PlainObjectMetaMethodSite#doInvoke: POST request to https://repo.jenkins-ci.org/api/security/token returned error: HTTP 400 Bad Request
WARNING	o.c.g.r.c.PlainObjectMetaMethodSite#doInvoke: Failed to generate token for jenkinsci/apache-httpcomponents-client-4-api-plugin
java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo.jenkins-ci.org/api/security/token
…
	at io.jenkins.infra.repository_permissions_updater.ArtifactoryAPI$ArtifactoryImpl$_generateTokenForGroup_closure2.doCall(ArtifactoryAPI.groovy:230)
	at io.jenkins.infra.repository_permissions_updater.ArtifactoryAPI$ArtifactoryImpl$_generateTokenForGroup_closure2.doCall(ArtifactoryAPI.groovy)
…
```

Those names are based on the GitHub repository names, with `CD-for-` prefix and replacing `/` with `__`.

CD tokens which are known to not be provisioned because of this length limitation:
* `CD-for-jenkinsci__apache-httpcomponents-client-4-api-plugin` (https://github.com/jenkins-infra/repository-permissions-updater/pull/2680)
* `CD-for-jenkinsci__compuware-topaz-for-enterprise-data-plugin` (https://github.com/jenkins-infra/repository-permissions-updater/pull/2600)

The longest known good token name is:
* `CD-for-jenkinsci__disable-github-multibranch-status-plugin`

The idea of these usernames is to make uploads attributable to a specific token, so the solution applied for group/permission target names of cutting them off after a certain length and appending a substring of a hash doesn't seem very desirable.

Perhaps shortening the prefix to `CD-` and shortening the very common `jenkinsci` to just `J`, or removing it altogether (leaving only the repo name without org name in the case of `jenkinsci`), could alleviate the problem for all reasonably named components?

**Comment by jetersen** [comment]
so the limit is 58 characters. The difference between `CD-for-jenkinsci__apache-httpcomponents-client-4-api-plugin` and `CD-for-jenkinsci__disable-github-multibranch-status-plugin` is one character.

You could also consider dropping the `-plugin`
So something like `CD-J-artifact-name`

**Comment by jetersen** [comment]
Looking at https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-CreateToken.1

I think it would be useful to use the `description` for the full repository path as it has a 1024 character limit and they even suggest to use that for filtering and managing tokens.

**Comment by jetersen** [comment]
Created https://github.com/jenkins-infra/repository-permissions-updater/pull/2683

**Comment by jetersen** [comment]
Think we can close this:

https://github.com/jenkins-infra/repository-permissions-updater/pull/2716 fixes the issue

**Comment by daniel-beck** [comment]
FTR https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/settings/secrets/actions has Maven secrets now.
