### ISSUE TITLE
[ERROR] Unknown lifecycle phase - On Build

### ISSUE THREAD

**Issue by pmezzomo** [jenkins-infra/repository-permissions-updater#2831]
### Reproduction steps

Hello!

When I try to build on Jenkins for a Java/Maven project, but I have this error:

> 
[ERROR] Unknown lifecycle phase "-". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

By the tests that I did the problem is in this command:
`clean install -Dgit-branch-name=${GIT_BRANCH_NAME} -Djenkins-build-tag=${BUILD_TAG}`

So I can try this: clean install , but it isn't work.

Does anyone know which command I should use to generate a build correctly?

I'm trying with these commands:

Goals: `versions:commit`

Goals:` clean install -Dgit-branch-name=${GIT_BRANCH_NAME} -Djenkins-build-tag=${BUILD_TAG}`

Goals: `versions:set -DnewVersion=1.0${BUILD_NUMBER}-SNAPSHOT`

Thank you!!

### Expected Results

I need a Jar for Deploy

### Actual Results

[ERROR] Unknown lifecycle phase "-". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

**Comment by MarkEWaite** [comment]
The issue tracker is used to track issues and enhancement requests.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
