### ISSUE TITLE
Provide maintainer information for prefix/wildcard hack plugins

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/repository-permissions-updater#2911]
### Reproduction steps

Several permissions files in this repository declare artifact names that do not match the actual component artifact IDs to work around the limitation of requiring one file per artifact ID, which can be cumbersome for multimodule repositories.

The most notable one of those is probably https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aws-java-sdk.yml which governs more than a dozen separate plugins.

As a side effect the update site does not find corresponding entries in https://reports.jenkins.io/maintainers.index.json for these plugins, and subsequently the plugins appear to have no maintainers on plugins.jenkins.io.

This practice should stop to allow https://github.com/jenkins-infra/update-center2/pull/654 to move forward.

### Expected Results

https://reports.jenkins.io/maintainers.index.json contains maintainer information for plugins whose permissions are currently specified using the "wildcard hack".

### Actual Results

It does not.

### Anything else?

It looks like the following plugins are currently using this hack:

- [`aws-java-sdk-*`](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aws-java-sdk.yml)
- [`mina-sshd-api-*`](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-mina-sshd-api.yml)

The `bom-*` does as well, but since it's not a plugin, its maintainers are not exposed elsewhere.

**Comment by timja** [comment]
Also https://github.com/jenkins-infra/repository-permissions-updater/pull/3538#issuecomment-1731970692

**Comment by daniel-beck** [comment]
Looking at the output diff with/without https://github.com/jenkins-infra/update-center2/pull/654 I noticed these would be up for adoption:

* aws-java-sdk2-logs
* aws-java-sdk2-cloudwatch
* aws-java-sdk2-api-gateway
* aws-java-sdk-cloudwatch

Looks like this fix is incomplete?

**Comment by timja** [comment]
None of these are mentioned in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aws-java-sdk2.yml

They need to be explicitly listed, cc @basil

**Comment by basil** [comment]
@timja Fixed in:

- https://github.com/jenkinsci/aws-java-sdk2-plugin/pull/30
- https://github.com/jenkinsci/bom/pull/4353
- https://github.com/jenkins-infra/repository-permissions-updater/pull/4283
- https://github.com/jenkins-infra/update-center2/pull/839
