### ISSUE TITLE
azure-publishersettings-credentials permissions do not match settings

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/repository-permissions-updater#2939]
### Reproduction steps

look at https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-azure-publishersettings-credentials.yml

then look at https://github.com/jenkinsci/azure-publishersettings-credentials-plugin/pull/13#issuecomment-1305850988

### Expected Results

I have admin / write access on this repository

### Actual Results

I have no access to write or admin this repo.

### Anything else?

@basil was the[ last to approve something](https://github.com/jenkinsci/azure-publishersettings-credentials-plugin/pull/11#pullrequestreview-1087212136) - although he is not listed here and his approval did not lead to a green tick (which is interesting in itself)

**Comment by NotMyFault** [comment]
> ### Expected Results
> I have admin / write access on this repository

The RPU's `developers` sequence is needed for release permission through the maven release plugin to artifactory (afaik) only, from a technical aspect. Not everyone listed must be added to the GH team associated with the repository and vice versa; not everyone added to the repository's team is added to the `developers` sequence here.

I see that you are part of the `@cloudbees-developers` team on the RPU, and therefore can publish releases of the plugin, but aren't part of the team associated with the repository.
Do you want me to add you to this team?

On the other hand, the jenkinsci org has a [company-cloudbees-developers](https://github.com/orgs/jenkinsci/teams/company-cloudbees-developers/)'s team. Maybe you could sync the member's list and list of repositories this team is added to with the [cloudbees member's list of the RPU ](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/teams/cloudbees-developers.yml) and RPU files this team is added to?

**Comment by timja** [comment]
Added cloudbees developers permissions
