### ISSUE TITLE
https://github.com/jenkinsci/okhttp-api-plugin missing permissions

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/repository-permissions-updater#3005]
### Reproduction steps

as per https://github.com/jenkinsci/okhttp-api-plugin/pull/125 and https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-okhttp-api.yml#L11

I am a member of cloudbees-developers but am missing write access to this repo.

Can the cloudbees-developers group please be added here please.

### Expected Results

I can merge PRs to the plugin

### Actual Results

I can not merge PRs to the plugin

### Anything else?

(similar to https://github.com/jenkins-infra/repository-permissions-updater/issues/2939)

**Comment by timja** [comment]
done
