### ISSUE TITLE
Delete lightstep-incident-response plugin

### ISSUE THREAD

**Issue by sn-priya-jagyasi** [jenkins-infra/repository-permissions-updater#3022]
Hi,

I worked on developing lightstep-incident-response-plugin. Now, we no longer need this [lightstep-incident-response-plugin](https://github.com/jenkinsci/lightstep-incident-response-plugin/ ) as Lightstep Incident Response application is shut down and would no longer continue to work. 
Hence, its integration with Jenkins will have to be removed, requesting to please delete this repository as I don't have access to do the same. Thank you.

**Comment by NotMyFault** [comment]
@timja can you archive the repository please? Let's rather not delete published plugins.

**Comment by sn-priya-jagyasi** [comment]
will archiving the repo, remove plugin documentation?

**Comment by NotMyFault** [comment]
> will archiving the repo, remove plugin documentation?

No, and I don't think that should be done. Archiving will set a clear sign that the project reached its end of life. 
You can also add the `deprecated` topic to the repository.

**Comment by sn-priya-jagyasi** [comment]
okay, do we need to update our plugin doc [https://plugins.jenkins.io/lightstep-incident-response/](https://plugins.jenkins.io/lightstep-incident-response/ ) ?

**Comment by NotMyFault** [comment]
The plugin has been suspended from the update center.
