### ISSUE TITLE
Add maintainer to Horreum Plugin

### ISSUE THREAD

**Issue by rvansa** [jenkins-infra/repository-permissions-updater#3031]
### GitHub repositories

https://github.com/jenkinsci/horreum-plugin

### GitHub users to have permission

[@jesperpedersen](https://github.com/jesperpedersen)

### Permission level

Maintain

### Justification

Jesper is taking over the maintenance of the whole Horreum project.

Thank you.

**Comment by NotMyFault** [comment]
Added!
