### ISSUE TITLE
BigPanda Plugin Developer Permissions

### ISSUE THREAD

**Issue by julioguereca** [jenkins-infra/repository-permissions-updater#3101]
### GitHub repositories

This repo
https://github.com/jenkinsci/bigpanda-plugin

### GitHub users to have permission

@julioguereca 
@goodwinjeremyr
@JuanDCardozo
@cjcrist
@lukej7
@PaulBaker27
@shikha-gaur

### Justification

Hello, 

We need to update the developers for the bigpanda plugin in the `permissions/plugin-bigpanda-jenkins.yml` 

- Remove`erikzaadi`
- My user has changed from `jguereca` to `julioguereca`. I have since deleted the `jguereca` user

**Comment by julioguereca** [comment]
@lukej7 FYI

**Comment by NotMyFault** [comment]
Hey,

> Remove `erikzaadi`

You can do that yourself if you file a pull request to this repository and remove them from your permission file: https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-bigpanda-jenkins.yml

> My user has changed from `jguereca` to `julioguereca`. I have since deleted the `jguereca` user

Same process applies like above.

I invited the users mentioned to the team associated with the repository.

**Comment by julioguereca** [comment]
@NotMyFault I did try creating a PR but was denied when attempting to push my local branch to the repo. The other user that we have in this project `robstemen` is currently on paternity leave

**Comment by NotMyFault** [comment]
> @NotMyFault I did try creating a PR but was denied when attempting to push my local branch to the repo. The other user that we have in this project `robstemen` is currently on paternity leave

Make sure you configured your fork as remote repository, instead of this repository because the latest change I can spot on your fork is from 2019.

**Comment by julioguereca** [comment]
@NotMyFault I might be misunderstanding the process I was trying to create a PR for this repo to update the developers for the plugin. 

Your comment about the fork, is that for this repo or for the plugin?

**Comment by NotMyFault** [comment]
> Your comment about the fork, is that for this repo or for the plugin?

It targets this repository. There is no up-to-date branch on [your fork of this repository](https://github.com/julioguereca/repository-permissions-updater/branches) from where you could file a PR which delivers the desired change. Hence, I mentioned the configuration above.

**Comment by julioguereca** [comment]
@NotMyFault Got it. This was my confusion. Thanks for the clarification

**Comment by NotMyFault** [comment]
Glad it worked out for you!
