### ISSUE TITLE
Add me as reviewer to lockable-resources-plugin

### ISSUE THREAD

**Issue by mark-reiche** [jenkins-infra/repository-permissions-updater#3113]
### GitHub repositories

https://github.com/jenkinsci/lockable-resources-plugin

### GitHub users to have permission

@mark-reiche

### Justification

As discussed with @mPokornyETM

**Comment by NotMyFault** [comment]
Added!

**Comment by mPokornyETM** [comment]
You are amazing, thx

**Comment by mark-reiche** [comment]
Nicht dafür ;-)

Am 30. Januar 2023 19:59:26 MEZ schrieb Martin Pokorny ***@***.***>:
>You are amazing, thx
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jenkins-infra/repository-permissions-updater/issues/3113#issuecomment-1409166028
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mPokornyETM** [comment]
> Nicht dafür ;-) Am 30. Januar 2023 19:59:26 MEZ schrieb Martin Pokorny ***@***.***>:
> You are amazing, thx -- Reply to this email directly or view it on GitHub: [#3113 (comment)](https://github.com/jenkins-infra/repository-permissions-updater/issues/3113#issuecomment-1409166028) You are receiving this because you authored the thread. Message ID: ***@***.***>
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

Steig in Gitter chat rein, da kann man gerne auch Deutsch reden. Ich würde mich sehr gerne die Ideen austauschen ;-)
