### ISSUE TITLE
Add @petejax to Helix ALM Test Management

### ISSUE THREAD

**Issue by vincenpt** [jenkins-infra/repository-permissions-updater#3144]
### GitHub repositories

https://github.com/jenkinsci/helix-alm-test-management-plugin

### GitHub users to have permission

@petejax

### Justification

When the Helix ALM Test Management plugin was approved ( https://github.com/jenkins-infra/repository-permissions-updater/issues/2813 ) @petejax was sent an invite to join the Jenkins organization, but he is not showing up as a current member. Maybe he didn't accept the invitation in a timely manner and it expired?

Could someone resend the invitation?

Thanks

**Comment by NotMyFault** [comment]
I send out a new invite. Invites are valid for 7 days only.

**Comment by pvince** [comment]
Thanks, that worked.
