### ISSUE TITLE
Plugin site

### ISSUE THREAD

**Issue by thyldrm** [jenkins-infra/repository-permissions-updater#3146]
### Describe your use-case which is not covered by existing documentation.

Hello, I have done a lot of necessary things. Now do I need to do anything for the plugin to be published here https://plugins.jenkins.io/ ?

- https://github.com/jenkins-infra/repository-permissions-updater/issues/3123
- https://github.com/jenkins-infra/repository-permissions-updater/pull/3139

**Comment by NotMyFault** [comment]
Please take a careful look at the CD documentation how to label PRs accordingly: https://www.jenkins.io/doc/developer/publishing/releasing-cd/#releasing

**Comment by thyldrm** [comment]
> You can also trigger a deployment explicitly, if the current commit has a passing check from Jenkins. Visit https://github.com/jenkinsci/your-plugin/actions?query=workflow%3Acd and click Run workflow. If you prefer to only deploy explicitly, not on every push, just comment out the check_run section in the workflow.

As per the description above I go to the link below;

https://github.com/jenkinsci/codethreat-scanner-plugin/actions?query=workflow%3Acd

But what I'm facing is;

> cd
Showing runs from all workflows named cd
0 workflow run results

**Comment by NotMyFault** [comment]
You didn't merge the PR where you enable CD yet, hence it doesn't show up.

**Comment by thyldrm** [comment]
Ok, I approved the PR and started the workflow. Do I need to do anything after this?

https://github.com/jenkinsci/codethreat-scanner-plugin/actions

**Comment by NotMyFault** [comment]
> Do I need to do anything after this?

Yes, as I told you before, read the documentation: https://www.jenkins.io/doc/developer/publishing/releasing-cd/#releasing

There are no PRs with interesting labels that would be picked up.

**Comment by thyldrm** [comment]
I added a label called devsecops

**Comment by thyldrm** [comment]
I don't understand how to PR for label here. What should I commit with PR?

**Comment by daniel-beck** [comment]
Labels for your pull request on GitHub, not labels for your plugin. You wouldn't want to create a new release for every merged dependency update, so this is how "interesting" PRs are identified.

**Comment by thyldrm** [comment]
i added label (enhancement) for this PR https://github.com/jenkinsci/codethreat-scanner-plugin/pull/2

**Comment by thyldrm** [comment]
I am writing again and again, I am aware that I have read the document, I have done the necessary things, is there anything I am missing?

- I triggered the workflow from https://github.com/jenkinsci/your-plugin/actions?query=workflow%3Acd here.

- https://github.com/jenkinsci/codethreat-scanner-plugin/pull/2 I added the label for this PR.

**Comment by NotMyFault** [comment]
Please trigger a new run of the workflow.

**Comment by thyldrm** [comment]
I did. (https://github.com/jenkinsci/codethreat-scanner-plugin/actions/runs/4192521483) Will it be published on "Plugin Site" now?

**Comment by NotMyFault** [comment]
Yes, anytime the job responsible for building the plugin pages run.

**Comment by thyldrm** [comment]
i don't see the plugin here yet https://plugins.jenkins.io/
