### ISSUE TITLE
Access to jenkinsci as member

### ISSUE THREAD

**Issue by accelq** [jenkins-infra/repository-permissions-updater#3171]
### GitHub repositories

Have lost access as a member of jenkinsci org. Due to this cannot push code to https://github.com/jenkinsci/accelq-ci-connect-plugin.

Request to re-send request to be a memeber of jenkinsci org.

### GitHub users to have permission

@accelq

### Justification

Lost access to jenkinsci. As the link was mistakenly removed. Jira ticket for reference. [https://issues.jenkins.io/browse/JENKINS-70736]

**Comment by NotMyFault** [comment]
@timja Can you check the audit log if the user left on their behalf or has been removed, please? 

I don't recall modifying this team's permission recently.

**Comment by daniel-beck** [comment]
They removed themselves from the org (and therefore the maintainers team).

**Comment by NotMyFault** [comment]
@accelq I send you an invitation.

**Comment by accelq** [comment]
thanks accepted
