### ISSUE TITLE
not getting a new release with cd?

### ISSUE THREAD

**Issue by thyldrm** [jenkins-infra/repository-permissions-updater#3202]
### Reproduction steps

1. I made a commit on my repo and merged the PR. Then, I ran the CD workflow from the action section, but it is skipping the release job

### Expected Results

Release job done

### Actual Results

https://github.com/jenkinsci/codethreat-scanner-plugin/actions/runs/4477951630

**Comment by daniel-beck** [comment]
CI must pass and it does not: https://github.com/jenkinsci/codethreat-scanner-plugin/runs/12123737871
