### ISSUE TITLE
new release is not released

### ISSUE THREAD

**Issue by thyldrm** [jenkins-infra/repository-permissions-updater#3220]
### Reproduction steps

I got an error a few days ago when I was building, I solved it now. The cd workflows worked without any problems. As you can see in ci.jenkins.io, there is a new build, but a new release has not been released, I could not find the reason for this. I don't want to bother you here, I apologize in advance. Thank you for your understanding.

### Expected Results

new release

### Actual Results

https://github.com/jenkinsci/codethreat-scanner-plugin/pull/5

https://ci.jenkins.io/job/Plugins/job/codethreat-scanner-plugin/job/master/5/

https://plugins.jenkins.io/codethreat-scanner/releases/

**Comment by NotMyFault** [comment]
Read the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/), you need to [label](https://github.com/jenkinsci/.github/blob/ce466227c534c42820a597cb8e9cac2f2334920a/.github/release-drafter.yml#L9-L37) your PRs accordingly to be considered by CD
