### ISSUE TITLE
update GitHub perms for aws-java-sdk-plugin

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/repository-permissions-updater#3252]
### GitHub repositories

https://github.com/jenkinsci/aws-java-sdk-plugin/

### GitHub users to have permission

the Group [@cloudbees-developers](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/teams/cloudbees-developers.yml) in RPU

```
alecharp
amuniz
aneveux
batmat
carroll
kerogers
mikecirioli
olamy
rarabaolaza
rsandell
teilo
twasyl
vlatombe
```

This could be https://github.com/orgs/jenkinsci/teams/company-cloudbees-developers/members (@kerogers and @dwnusbaum are missing from the team but are in the yaml, @escoem is in the team but not the YAML).  (not sure if this team is supposed to map to the yaml or not - if it is then I approve of adding @escoem)

### Justification

the users are already mentioned in the [plugins](https://github.com/jenkinsci/aws-java-sdk-plugin/blob/master/pom.xml#L11-L12) [entry](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aws-java-sdk.yml) in `r-p-u` but have no GitHub permissions to merge changes.

E.g.
https://github.com/jenkinsci/aws-java-sdk-plugin/pull/973#issuecomment-1511365963

**Comment by timja** [comment]
done, only @Vlatombe had access before

**Comment by jtnord** [comment]
Thanks @timja
