### ISSUE TITLE
bastiandoetsch requested to join "snyk-security-scanner-plugin Developers"

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/repository-permissions-updater#3392]
### GitHub repositories

https://github.com/jenkinsci/snyk-security-scanner-plugin

### GitHub users to have permission

@bastiandoetsch

### Justification

Not my request per se, but as I rejected his request to join the team directly, it's a way to show him the expected path forward in the project.

**Comment by Wadeck** [comment]
@bastiandoetsch Please confirm your interest to become a maintainer for the snyk-security-scanner plugin, so that the other maintainers can approve or reject the request in this issue :)

**Comment by bastiandoetsch** [comment]
Hi @Wadeck , as far as I know, I already have these permissions. But yes, I should be a maintainer :).

**Comment by bastiandoetsch** [comment]
I just joined the team, because direct, non-team permissions are a bit messier. I'm an Admin on that repo, though.

**Comment by daniel-beck** [comment]
@bastiandoetsch We're happy to make someone from the maintainers group the "team maintainer" so they can add and remove team members.

Otherwise, we manage permissions directly via a bot, and every maintainer should also be a team member, or something went wrong when they were added in a PR to this repo.

Only folks who should be able to commit, but not to publish new releases, would need to be managed directly by other maintainers.

**Comment by bastiandoetsch** [comment]
Ah thanks! I'll discuss with the team, who's gonna be the one!

**Comment by daniel-beck** [comment]
We can add multiple folks as well.

As a general reminder though, removing people from the repo but not the files in this repo does not take away their ability to publish new releases.

**Comment by bastiandoetsch** [comment]
Ah, that sounds excellent. We have a [PR open](https://github.com/jenkins-infra/repository-permissions-updater/pull/3395) to update the maintainers list - could all three new entries be team maintainers?

**Comment by NotMyFault** [comment]
> three new entries

Am I missing something? https://github.com/jenkins-infra/repository-permissions-updater/pull/3395/files does only remove users. Let me know their GH handle, and we can add them.

**Comment by NotMyFault** [comment]
Closing, as the submitters are no longer interested in moving the issue forward, as indicated by the lack of a response.
