### ISSUE TITLE
Add `lemeurherve` (Jenkins user `hlemeur`) to jenkinsci/docker-agent

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/repository-permissions-updater#3423]
### GitHub repositories

https://github.com/jenkinsci/docker-agent

### GitHub users to have permission

@lemeurherve 

### Justification

I'd like to help maintaining this repository, and this addition would also allow me to avoid replaying my builds almost every time.

Contributions: https://github.com/jenkinsci/docker-agent/pulls?q=is%3Apr+author%3Alemeurherve

**Comment by lemeurherve** [comment]
cc @dduportal @MarkEWaite @olblak @timja @oleg-nenashev (https://github.com/orgs/jenkinsci/teams/team-docker-packaging)

**Comment by MarkEWaite** [comment]
+1 from me

**Comment by NotMyFault** [comment]
Added!
