### ISSUE TITLE
Grant New Delphix Commit and Release Access

### ISSUE THREAD

**Issue by nick-mathison** [jenkins-infra/repository-permissions-updater#3426]
### GitHub repositories

https://github.com/jenkinsci/delphix-plugin

### GitHub users to have permission

@arunskurian
@ankit-patil-hubs
@nick-mathison
@sunnyx4

### Justification

We are the current working team from Delphix building and managing the revised Delphix plugin. 

All of these users should have permission to commit, merge, and release new versions of the plugin.

**Comment by nick-mathison** [comment]
Other qualifying PRs

https://github.com/jenkins-infra/update-center2/pull/695
https://github.com/jenkins-infra/update-center2/pull/725
https://github.com/delphix/delphix-plugin

**Comment by NotMyFault** [comment]
Added!

**Comment by NotMyFault** [comment]
Although, to be able to cut releases, you need to add your username used to sign up on [accounts.jenkins.io](https://accounts.jenkins.io/) the [permission file](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-delphix.yml) of the plugin.
