### ISSUE TITLE
Grant Additional Delphix Permissions

### ISSUE THREAD

**Issue by nick-mathison** [jenkins-infra/repository-permissions-updater#3440]
### GitHub repositories

https://github.com/jenkinsci/delphix-plugin

### GitHub users to have permission

@elima-sugunan
@Uddipaan-Hazarika

### Justification

Write permissions on the Delphix GitHub branch to help merge and release the plugin.

**Comment by NotMyFault** [comment]
Added, for release permissions, raise a PR.
