### ISSUE TITLE
Add a comment on merged PRs to explain what's next and the time window

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/repository-permissions-updater#3494]
### What feature do you want to see added?

I think it could be nice to add an automatic comment on PRs here after their merge explaining what are the next steps and the timing (of token availability for example)

Recent related helpdesk issue with explanations: https://github.com/jenkins-infra/helpdesk/issues/3723#issuecomment-1688032023

**Comment by NotMyFault** [comment]
The user of the helpdesk issue was extremely impatient with their hosting and CD request, commonly submitters read our responses and wait a few hours after their CD PR has been merged.

**Comment by daniel-beck** [comment]
Specifically the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#enable-cd-permissions) states:

> Once [the CD enablement PR] has been merged, start checking https://github.com/jenkinsci/your-plugin/settings/secrets/actions until you see `MAVEN_TOKEN` and `MAVEN_USERNAME` appear under **Repository secrets**.

Still seems like this would make a nice improvement. The information exists, but could benefit from readily being visible where it's needed. Not a "bug" though :)
