### ISSUE TITLE
Set GitHub homepage to plugin site when accepting a hosting request

### ISSUE THREAD

**Issue by basil** [jenkins-infra/repository-permissions-updater#3573]
In #3503, https://github.com/jenkinsci/redhat-dependency-analytics-plugin was created without a GitHub homepage set. Following existing practice in popular plugins, I set the GitHub homepage to https://plugins.jenkins.io/redhat-dependency-analytics/ but it would be nice if this was done automatically when accepting the hosting request.

**Comment by basil** [comment]
Why was https://github.com/jenkinsci/harbor-plugin created without a link to https://plugins.jenkins.io/harbor/?

**Comment by timja** [comment]
because it is not in the automation.

**Comment by basil** [comment]
Should it be done manually in the meantime?

**Comment by timja** [comment]
Not in my opinion, anything that is expected to be done should be in the automation.

I have no expectation for hosting team members to be doing things manually separately.

**Comment by basil** [comment]
I would expect it to be done for consistency with existing hosted repositories, regardless of whether it is currently covered by automation.

**Comment by timja** [comment]
> I would expect it to be done for consistency with existing hosted repositories, regardless of whether it is currently covered by automation.

You are welcome to your expectations, but it is not a requirement of the hosting team.

The requirements for what happens when hosting a plugin are codified, not in wish-lists.

**Comment by basil** [comment]
> The requirements for what happens when hosting a plugin are codified

Thanks Tim, I think this should be codified as a requirement so that newly-hosted repositories are consistent with existing ones.
