### ISSUE TITLE
Add user to gradle-jte-plugin, we may have forgotten how to DIY

### ISSUE THREAD

**Issue by cokieffebah** [jenkins-infra/repository-permissions-updater#4010]
### GitHub repositories

https://github.com/jenkinsci/gradle-jte-plugin

### GitHub users to have permission

@cokieffebah 

### Justification

@cokieffebah,me, is a developer for most of the JTE code and was not initially added to the gradle jte plugin but is on the jte plugin with @steven-terrana.  We were not able to figure out how to update the gradle-jte-plugin to add me.
Thanks in advance and feel free to provide instructions.

**Comment by timja** [comment]
I can't see a repository file for this (although I may be missing it) we can add you to the repo if @steven-terrana approves it

**Comment by steven-terrana** [comment]
I approve. 

I also couldn't find the permissions file which is why we made an issue for this. 

I appreciate your help!

**Comment by timja** [comment]
done if someone is a member of the org (which Carlos is) you can add the person here https://github.com/orgs/jenkinsci/teams/gradle-jte-plugin-developers/members

**Comment by cokieffebah** [comment]
thanks @timja
