### ISSUE TITLE
Permissions on kubernetes-credentials repo do not match with RPU developer list

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/repository-permissions-updater#4039]
### Reproduction steps

1. Developers that are part of a team in the [kubernetes credentials plugin permissions YAML file](https://github.com/jenkins-infra/repository-permissions-updater/blob/b2f5da3c77ec17dce4ffed0685e8026dace770e8/permissions/plugin-kubernetes-credentials.yml#L14) should be able to merge pull requests but do not have permission to merge.  @raul-arabaolaza and @alecharp are both in the team that is part of the developers list, but neither is allowed to merge

### Expected Results

Members of a team that are in the developers list for the repository should be able to merge pull requests

### Actual Results

Several members of the team that are in the developers list for the repository are not able to merge pull requests

### Anything else?

We need to release a new version of kubernetes credentials plugin before the end of this week so that we can include that update in the release of the plugin bill of materials that will include Jenkins 2.472 with Jetty 12 EE 8.

**Comment by MarkEWaite** [comment]
We have a workaround since Basil Crow has enough permissions to perform the merge.

**Comment by timja** [comment]
done
