### ISSUE TITLE
Place "olamy" in git plugin developers and git client plugin developers groups

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/repository-permissions-updater#4054]
### GitHub repositories

Olivier Lamy is authorized in repository permissions updater data files ([here](https://github.com/jenkins-infra/repository-permissions-updater/blob/f472215ee801b3f1e633f35c7ca95bc1e559bd4f/permissions/plugin-git-client.yml#L12) and [here](https://github.com/jenkins-infra/repository-permissions-updater/blob/f472215ee801b3f1e633f35c7ca95bc1e559bd4f/permissions/plugin-git.yml#L13)) for:

* https://github.com/orgs/jenkinsci/teams/git-client-plugin-developers
* https://github.com/orgs/jenkinsci/teams/git-plugin-developers

but is not included in either of those groups.  I'll be out of the office for almost two weeks and need to be sure that @olamy has the needed permissions.

### GitHub users to have permission

@olamy 

### Justification

Olivier Lamy is already authorized per the permissions file and can merge pull request in at least one of those repositories, but is not in the designated GitHub team.  I'd like him to be included in the GitHub team.

**Comment by timja** [comment]
Done
