### ISSUE TITLE
No Write Access to Aqua Scanner Plugin

### ISSUE THREAD

**Issue by KoppulaRajender** [jenkins-infra/repository-permissions-updater#4057]
### GitHub repositories

https://github.com/jenkinsci/aqua-security-scanner-plugin

### GitHub users to have permission

@KoppulaRajender @ppandrangi

### Justification

The mentioned GitHub users have already updated the permissions file for the Aqua Security Scanner plugin. However, we are still unable to merge the pull request, despite it passing all tests. we require write access to merge pull requests into the plugin repository (https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aqua-security-scanner.yml)

example PR: https://bitbucket.org/scalock/wave-deployments/pull-requests/299 - no write access to merge the PR.

**Comment by timja** [comment]
You were able to 10 months ago, I assume you left the organisation at some point.

I've re-added you, please go to https://github.com/jenkinsci to accept the invite
