### ISSUE TITLE
No Write Access to Aqua Scanner Plugin

### ISSUE THREAD

**Issue by nsreenivas0731** [jenkins-infra/repository-permissions-updater#4074]
### GitHub repositories

https://github.com/jenkinsci/aqua-security-scanner-plugin

### GitHub users to have permission

@nsreenivas0731 

### Justification

The mentioned GitHub users have already updated the permissions file for the Aqua Security Scanner plugin. However, we are still unable to merge the pull request, despite it passing all tests. we require write access to merge pull requests into the plugin repository (https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aqua-security-scanner.yml)

example PR: https://github.com/jenkinsci/aqua-security-scanner-plugin/pull/56 - no write access to merge the PR.

**Comment by timja** [comment]
You were sent an invite a few hours ago:
<img width="549" alt="image" src="https://github.com/user-attachments/assets/f0287ab4-3862-4817-8341-3a31f9b037ff">

Please go to https://github.com/jenkinsci to accept it
