### ISSUE TITLE
Request push permissions for repository-permissions-updater

### ISSUE THREAD

**Issue by cotovanu-cristian** [jenkins-infra/repository-permissions-updater#4142]
### GitHub repositories

[repository-permissions-updater](https://github.com/jenkins-infra/repository-permissions-updater)

### GitHub users to have permission

@cotovanu-cristian

### Justification

Hello

I am onboarding the `uipath-automation-package-plugin` Jenkins plugin to the cd release procedure so I would like to be able to push a branch/open PR/merge PR in the [repository-permissions-updater](https://github.com/jenkins-infra/repository-permissions-updater) repository.
Justification is that I am a developer and an admin of the repository https://github.com/jenkinsci/uipath-automation-package-plugin. I also have the jenkins artifactory and jira account, `cristiancotovanu` is the username (if relevant).

Thank you!

**Comment by timja** [comment]
Please fork it - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

Or just use the GitHub UI for editing it and it will do that automatically for you.
