### ISSUE TITLE
No Write Access to Aqua Scanner Plugin

### ISSUE THREAD

**Issue by behara** [jenkins-infra/repository-permissions-updater#4225]
### GitHub repositories

https://github.com/jenkinsci/aqua-security-scanner-plugin

### GitHub users to have permission

@behara @y-udaykiran96 

### Justification

GitHub repositories
https://github.com/jenkinsci/aqua-security-scanner-plugin

GitHub users to have permission
@behara @y-udaykiran96 

Justification
The mentioned GitHub users have already updated the permissions file for the Aqua Security Scanner plugin. However, we are still unable to merge the pull request, despite it passing all tests. we require write access to merge pull requests into the plugin repository (https://github.com/jenkins-infra/repository-permissions-updater/blob/45ce5839b233b1da85b3dbb176796d3470a0e6b5/permissions/plugin-aqua-security-scanner.yml#L19, https://github.com/jenkins-infra/repository-permissions-updater/blob/45ce5839b233b1da85b3dbb176796d3470a0e6b5/permissions/plugin-aqua-security-scanner.yml#L20)

**Comment by behara** [comment]
@timja can you review ?

**Comment by timja** [comment]
Looks like @alecharp added you both without the GitHub permissions.

Done now
