### ISSUE TITLE
Hosting checker didn't fail when no GitHub user or Jenkins project users

### ISSUE THREAD

**Issue by timja** [jenkins-infra/repository-permissions-updater#4231]
### Reproduction steps

see https://github.com/jenkins-infra/repository-permissions-updater/issues/4204

```markdown
### Repository URL

https://github.com/Simplify3x/simplifyqa-pipeline-executor-plugin

### New Repository Name

simplifyqa-pipeline-executor-plugin

### Description

when i build the plugins with the parameters,it will execute the testcase and execute the pipelines in simplifyQA.

### GitHub users to have commit permission

### Jenkins project users to have release permission

### Issue tracker

GitHub issues
```

and https://github.com/jenkins-infra/repository-permissions-updater/issues/4204#issuecomment-2540104970

### Expected Results

Ensured at least one of each specified

### Actual Results

Passed and failed on the PR for hosting (developers list empty: https://github.com/jenkins-infra/repository-permissions-updater/pull/4230/commits/c11532f59560cc19105da9db84e1d294695e5f60)

**Comment by Simplify3x** [comment]
what is bug here

**Comment by timja** [comment]
The hosting verifier wrongly marked hosting as successful when there was no users, which made parts of the process fail later that I had to manually fix
